// Code generated by gowsdl DO NOT EDIT.

package service

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

type customTime struct {
    time.Time
}

func (c *customTime) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
    const shortForm = "2006-01-02T15:04:05"
    var v string
	d.DecodeElement(&v, &start)
	if v != "" {
		parse, err := time.Parse(shortForm, v)
		if err != nil {
			return err
		}
		*c = customTime{parse}
	}
    
    return nil
}

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

//
// Two-letter (alpha-2) ISO 3166-1 code for one of the 243 countries.
//

type ISO3166CountyCode string

const (
	ISO3166CountyCodeAF ISO3166CountyCode = "AF"

	ISO3166CountyCodeAX ISO3166CountyCode = "AX"

	ISO3166CountyCodeAL ISO3166CountyCode = "AL"

	ISO3166CountyCodeDZ ISO3166CountyCode = "DZ"

	ISO3166CountyCodeAS ISO3166CountyCode = "AS"

	ISO3166CountyCodeAD ISO3166CountyCode = "AD"

	ISO3166CountyCodeAO ISO3166CountyCode = "AO"

	ISO3166CountyCodeAI ISO3166CountyCode = "AI"

	ISO3166CountyCodeAQ ISO3166CountyCode = "AQ"

	ISO3166CountyCodeAG ISO3166CountyCode = "AG"

	ISO3166CountyCodeAR ISO3166CountyCode = "AR"

	ISO3166CountyCodeAM ISO3166CountyCode = "AM"

	ISO3166CountyCodeAW ISO3166CountyCode = "AW"

	ISO3166CountyCodeAU ISO3166CountyCode = "AU"

	ISO3166CountyCodeAT ISO3166CountyCode = "AT"

	ISO3166CountyCodeAZ ISO3166CountyCode = "AZ"

	ISO3166CountyCodeBS ISO3166CountyCode = "BS"

	ISO3166CountyCodeBH ISO3166CountyCode = "BH"

	ISO3166CountyCodeBD ISO3166CountyCode = "BD"

	ISO3166CountyCodeBB ISO3166CountyCode = "BB"

	ISO3166CountyCodeBY ISO3166CountyCode = "BY"

	ISO3166CountyCodeBE ISO3166CountyCode = "BE"

	ISO3166CountyCodeBZ ISO3166CountyCode = "BZ"

	ISO3166CountyCodeBJ ISO3166CountyCode = "BJ"

	ISO3166CountyCodeBM ISO3166CountyCode = "BM"

	ISO3166CountyCodeBT ISO3166CountyCode = "BT"

	ISO3166CountyCodeBO ISO3166CountyCode = "BO"

	ISO3166CountyCodeBA ISO3166CountyCode = "BA"

	ISO3166CountyCodeBW ISO3166CountyCode = "BW"

	ISO3166CountyCodeBV ISO3166CountyCode = "BV"

	ISO3166CountyCodeBR ISO3166CountyCode = "BR"

	ISO3166CountyCodeIO ISO3166CountyCode = "IO"

	ISO3166CountyCodeBN ISO3166CountyCode = "BN"

	ISO3166CountyCodeBG ISO3166CountyCode = "BG"

	ISO3166CountyCodeBF ISO3166CountyCode = "BF"

	ISO3166CountyCodeBI ISO3166CountyCode = "BI"

	ISO3166CountyCodeKH ISO3166CountyCode = "KH"

	ISO3166CountyCodeCM ISO3166CountyCode = "CM"

	ISO3166CountyCodeCA ISO3166CountyCode = "CA"

	ISO3166CountyCodeCV ISO3166CountyCode = "CV"

	ISO3166CountyCodeKY ISO3166CountyCode = "KY"

	ISO3166CountyCodeCF ISO3166CountyCode = "CF"

	ISO3166CountyCodeTD ISO3166CountyCode = "TD"

	ISO3166CountyCodeCL ISO3166CountyCode = "CL"

	ISO3166CountyCodeCN ISO3166CountyCode = "CN"

	ISO3166CountyCodeCX ISO3166CountyCode = "CX"

	ISO3166CountyCodeCC ISO3166CountyCode = "CC"

	ISO3166CountyCodeCO ISO3166CountyCode = "CO"

	ISO3166CountyCodeKM ISO3166CountyCode = "KM"

	ISO3166CountyCodeCG ISO3166CountyCode = "CG"

	ISO3166CountyCodeCD ISO3166CountyCode = "CD"

	ISO3166CountyCodeCK ISO3166CountyCode = "CK"

	ISO3166CountyCodeCR ISO3166CountyCode = "CR"

	ISO3166CountyCodeCI ISO3166CountyCode = "CI"

	ISO3166CountyCodeHR ISO3166CountyCode = "HR"

	ISO3166CountyCodeCU ISO3166CountyCode = "CU"

	ISO3166CountyCodeCY ISO3166CountyCode = "CY"

	ISO3166CountyCodeCZ ISO3166CountyCode = "CZ"

	ISO3166CountyCodeDK ISO3166CountyCode = "DK"

	ISO3166CountyCodeDJ ISO3166CountyCode = "DJ"

	ISO3166CountyCodeDM ISO3166CountyCode = "DM"

	ISO3166CountyCodeDO ISO3166CountyCode = "DO"

	ISO3166CountyCodeEC ISO3166CountyCode = "EC"

	ISO3166CountyCodeEG ISO3166CountyCode = "EG"

	ISO3166CountyCodeSV ISO3166CountyCode = "SV"

	ISO3166CountyCodeGQ ISO3166CountyCode = "GQ"

	ISO3166CountyCodeER ISO3166CountyCode = "ER"

	ISO3166CountyCodeEE ISO3166CountyCode = "EE"

	ISO3166CountyCodeET ISO3166CountyCode = "ET"

	ISO3166CountyCodeFK ISO3166CountyCode = "FK"

	ISO3166CountyCodeFO ISO3166CountyCode = "FO"

	ISO3166CountyCodeFJ ISO3166CountyCode = "FJ"

	ISO3166CountyCodeFI ISO3166CountyCode = "FI"

	ISO3166CountyCodeFR ISO3166CountyCode = "FR"

	ISO3166CountyCodeGF ISO3166CountyCode = "GF"

	ISO3166CountyCodePF ISO3166CountyCode = "PF"

	ISO3166CountyCodeTF ISO3166CountyCode = "TF"

	ISO3166CountyCodeGA ISO3166CountyCode = "GA"

	ISO3166CountyCodeGM ISO3166CountyCode = "GM"

	ISO3166CountyCodeGE ISO3166CountyCode = "GE"

	ISO3166CountyCodeDE ISO3166CountyCode = "DE"

	ISO3166CountyCodeGH ISO3166CountyCode = "GH"

	ISO3166CountyCodeGI ISO3166CountyCode = "GI"

	ISO3166CountyCodeGR ISO3166CountyCode = "GR"

	ISO3166CountyCodeGL ISO3166CountyCode = "GL"

	ISO3166CountyCodeGD ISO3166CountyCode = "GD"

	ISO3166CountyCodeGP ISO3166CountyCode = "GP"

	ISO3166CountyCodeGU ISO3166CountyCode = "GU"

	ISO3166CountyCodeGT ISO3166CountyCode = "GT"

	ISO3166CountyCodeGG ISO3166CountyCode = "GG"

	ISO3166CountyCodeGN ISO3166CountyCode = "GN"

	ISO3166CountyCodeGW ISO3166CountyCode = "GW"

	ISO3166CountyCodeGY ISO3166CountyCode = "GY"

	ISO3166CountyCodeHT ISO3166CountyCode = "HT"

	ISO3166CountyCodeHM ISO3166CountyCode = "HM"

	ISO3166CountyCodeVA ISO3166CountyCode = "VA"

	ISO3166CountyCodeHN ISO3166CountyCode = "HN"

	ISO3166CountyCodeHK ISO3166CountyCode = "HK"

	ISO3166CountyCodeHU ISO3166CountyCode = "HU"

	ISO3166CountyCodeIS ISO3166CountyCode = "IS"

	ISO3166CountyCodeIN ISO3166CountyCode = "IN"

	ISO3166CountyCodeID ISO3166CountyCode = "ID"

	ISO3166CountyCodeIR ISO3166CountyCode = "IR"

	ISO3166CountyCodeIQ ISO3166CountyCode = "IQ"

	ISO3166CountyCodeIE ISO3166CountyCode = "IE"

	ISO3166CountyCodeIM ISO3166CountyCode = "IM"

	ISO3166CountyCodeIL ISO3166CountyCode = "IL"

	ISO3166CountyCodeIT ISO3166CountyCode = "IT"

	ISO3166CountyCodeJM ISO3166CountyCode = "JM"

	ISO3166CountyCodeJP ISO3166CountyCode = "JP"

	ISO3166CountyCodeJE ISO3166CountyCode = "JE"

	ISO3166CountyCodeJO ISO3166CountyCode = "JO"

	ISO3166CountyCodeKZ ISO3166CountyCode = "KZ"

	ISO3166CountyCodeKE ISO3166CountyCode = "KE"

	ISO3166CountyCodeKI ISO3166CountyCode = "KI"

	ISO3166CountyCodeKP ISO3166CountyCode = "KP"

	ISO3166CountyCodeKR ISO3166CountyCode = "KR"

	ISO3166CountyCodeKW ISO3166CountyCode = "KW"

	ISO3166CountyCodeKG ISO3166CountyCode = "KG"

	ISO3166CountyCodeLA ISO3166CountyCode = "LA"

	ISO3166CountyCodeLV ISO3166CountyCode = "LV"

	ISO3166CountyCodeLB ISO3166CountyCode = "LB"

	ISO3166CountyCodeLS ISO3166CountyCode = "LS"

	ISO3166CountyCodeLR ISO3166CountyCode = "LR"

	ISO3166CountyCodeLY ISO3166CountyCode = "LY"

	ISO3166CountyCodeLI ISO3166CountyCode = "LI"

	ISO3166CountyCodeLT ISO3166CountyCode = "LT"

	ISO3166CountyCodeLU ISO3166CountyCode = "LU"

	ISO3166CountyCodeMO ISO3166CountyCode = "MO"

	ISO3166CountyCodeMK ISO3166CountyCode = "MK"

	ISO3166CountyCodeMG ISO3166CountyCode = "MG"

	ISO3166CountyCodeMW ISO3166CountyCode = "MW"

	ISO3166CountyCodeMY ISO3166CountyCode = "MY"

	ISO3166CountyCodeMV ISO3166CountyCode = "MV"

	ISO3166CountyCodeML ISO3166CountyCode = "ML"

	ISO3166CountyCodeMT ISO3166CountyCode = "MT"

	ISO3166CountyCodeMH ISO3166CountyCode = "MH"

	ISO3166CountyCodeMQ ISO3166CountyCode = "MQ"

	ISO3166CountyCodeMR ISO3166CountyCode = "MR"

	ISO3166CountyCodeMU ISO3166CountyCode = "MU"

	ISO3166CountyCodeYT ISO3166CountyCode = "YT"

	ISO3166CountyCodeMX ISO3166CountyCode = "MX"

	ISO3166CountyCodeFM ISO3166CountyCode = "FM"

	ISO3166CountyCodeMD ISO3166CountyCode = "MD"

	ISO3166CountyCodeMC ISO3166CountyCode = "MC"

	ISO3166CountyCodeMN ISO3166CountyCode = "MN"

	ISO3166CountyCodeMS ISO3166CountyCode = "MS"

	ISO3166CountyCodeMA ISO3166CountyCode = "MA"

	ISO3166CountyCodeMZ ISO3166CountyCode = "MZ"

	ISO3166CountyCodeMM ISO3166CountyCode = "MM"

	ISO3166CountyCodeNA ISO3166CountyCode = "NA"

	ISO3166CountyCodeNR ISO3166CountyCode = "NR"

	ISO3166CountyCodeNP ISO3166CountyCode = "NP"

	ISO3166CountyCodeNL ISO3166CountyCode = "NL"

	ISO3166CountyCodeAN ISO3166CountyCode = "AN"

	ISO3166CountyCodeNC ISO3166CountyCode = "NC"

	ISO3166CountyCodeNZ ISO3166CountyCode = "NZ"

	ISO3166CountyCodeNI ISO3166CountyCode = "NI"

	ISO3166CountyCodeNE ISO3166CountyCode = "NE"

	ISO3166CountyCodeNG ISO3166CountyCode = "NG"

	ISO3166CountyCodeNU ISO3166CountyCode = "NU"

	ISO3166CountyCodeNF ISO3166CountyCode = "NF"

	ISO3166CountyCodeMP ISO3166CountyCode = "MP"

	ISO3166CountyCodeNO ISO3166CountyCode = "NO"

	ISO3166CountyCodeOM ISO3166CountyCode = "OM"

	ISO3166CountyCodePK ISO3166CountyCode = "PK"

	ISO3166CountyCodePW ISO3166CountyCode = "PW"

	ISO3166CountyCodePS ISO3166CountyCode = "PS"

	ISO3166CountyCodePA ISO3166CountyCode = "PA"

	ISO3166CountyCodePG ISO3166CountyCode = "PG"

	ISO3166CountyCodePY ISO3166CountyCode = "PY"

	ISO3166CountyCodePE ISO3166CountyCode = "PE"

	ISO3166CountyCodePH ISO3166CountyCode = "PH"

	ISO3166CountyCodePN ISO3166CountyCode = "PN"

	ISO3166CountyCodePL ISO3166CountyCode = "PL"

	ISO3166CountyCodePT ISO3166CountyCode = "PT"

	ISO3166CountyCodePR ISO3166CountyCode = "PR"

	ISO3166CountyCodeQA ISO3166CountyCode = "QA"

	ISO3166CountyCodeRE ISO3166CountyCode = "RE"

	ISO3166CountyCodeRO ISO3166CountyCode = "RO"

	ISO3166CountyCodeRU ISO3166CountyCode = "RU"

	ISO3166CountyCodeRW ISO3166CountyCode = "RW"

	ISO3166CountyCodeSH ISO3166CountyCode = "SH"

	ISO3166CountyCodeKN ISO3166CountyCode = "KN"

	ISO3166CountyCodeLC ISO3166CountyCode = "LC"

	ISO3166CountyCodePM ISO3166CountyCode = "PM"

	ISO3166CountyCodeVC ISO3166CountyCode = "VC"

	ISO3166CountyCodeWS ISO3166CountyCode = "WS"

	ISO3166CountyCodeSM ISO3166CountyCode = "SM"

	ISO3166CountyCodeST ISO3166CountyCode = "ST"

	ISO3166CountyCodeSA ISO3166CountyCode = "SA"

	ISO3166CountyCodeSN ISO3166CountyCode = "SN"

	ISO3166CountyCodeCS ISO3166CountyCode = "CS"

	ISO3166CountyCodeSC ISO3166CountyCode = "SC"

	ISO3166CountyCodeSL ISO3166CountyCode = "SL"

	ISO3166CountyCodeSG ISO3166CountyCode = "SG"

	ISO3166CountyCodeSK ISO3166CountyCode = "SK"

	ISO3166CountyCodeSI ISO3166CountyCode = "SI"

	ISO3166CountyCodeSB ISO3166CountyCode = "SB"

	ISO3166CountyCodeSO ISO3166CountyCode = "SO"

	ISO3166CountyCodeZA ISO3166CountyCode = "ZA"

	ISO3166CountyCodeGS ISO3166CountyCode = "GS"

	ISO3166CountyCodeES ISO3166CountyCode = "ES"

	ISO3166CountyCodeLK ISO3166CountyCode = "LK"

	ISO3166CountyCodeSD ISO3166CountyCode = "SD"

	ISO3166CountyCodeSR ISO3166CountyCode = "SR"

	ISO3166CountyCodeSJ ISO3166CountyCode = "SJ"

	ISO3166CountyCodeSZ ISO3166CountyCode = "SZ"

	ISO3166CountyCodeSE ISO3166CountyCode = "SE"

	ISO3166CountyCodeCH ISO3166CountyCode = "CH"

	ISO3166CountyCodeSY ISO3166CountyCode = "SY"

	ISO3166CountyCodeTW ISO3166CountyCode = "TW"

	ISO3166CountyCodeTJ ISO3166CountyCode = "TJ"

	ISO3166CountyCodeTZ ISO3166CountyCode = "TZ"

	ISO3166CountyCodeTH ISO3166CountyCode = "TH"

	ISO3166CountyCodeTL ISO3166CountyCode = "TL"

	ISO3166CountyCodeTG ISO3166CountyCode = "TG"

	ISO3166CountyCodeTK ISO3166CountyCode = "TK"

	ISO3166CountyCodeTO ISO3166CountyCode = "TO"

	ISO3166CountyCodeTT ISO3166CountyCode = "TT"

	ISO3166CountyCodeTN ISO3166CountyCode = "TN"

	ISO3166CountyCodeTR ISO3166CountyCode = "TR"

	ISO3166CountyCodeTM ISO3166CountyCode = "TM"

	ISO3166CountyCodeTC ISO3166CountyCode = "TC"

	ISO3166CountyCodeTV ISO3166CountyCode = "TV"

	ISO3166CountyCodeUG ISO3166CountyCode = "UG"

	ISO3166CountyCodeUA ISO3166CountyCode = "UA"

	ISO3166CountyCodeAE ISO3166CountyCode = "AE"

	ISO3166CountyCodeGB ISO3166CountyCode = "GB"

	ISO3166CountyCodeUS ISO3166CountyCode = "US"

	ISO3166CountyCodeUM ISO3166CountyCode = "UM"

	ISO3166CountyCodeUY ISO3166CountyCode = "UY"

	ISO3166CountyCodeUZ ISO3166CountyCode = "UZ"

	ISO3166CountyCodeVU ISO3166CountyCode = "VU"

	ISO3166CountyCodeVE ISO3166CountyCode = "VE"

	ISO3166CountyCodeVN ISO3166CountyCode = "VN"

	ISO3166CountyCodeVG ISO3166CountyCode = "VG"

	ISO3166CountyCodeVI ISO3166CountyCode = "VI"

	ISO3166CountyCodeWF ISO3166CountyCode = "WF"

	ISO3166CountyCodeEH ISO3166CountyCode = "EH"

	ISO3166CountyCodeYE ISO3166CountyCode = "YE"

	ISO3166CountyCodeZM ISO3166CountyCode = "ZM"

	ISO3166CountyCodeZW ISO3166CountyCode = "ZW"
)

type CurrencyNameType string

const (
	CurrencyNameTypeAfghanistanAfghani CurrencyNameType = "Afghanistan Afghani"

	CurrencyNameTypeAlbaniaLek CurrencyNameType = "Albania Lek"

	CurrencyNameTypeAlgerianDinar CurrencyNameType = "Algerian Dinar"

	CurrencyNameTypeAngolaNewKwanza CurrencyNameType = "Angola New Kwanza"

	CurrencyNameTypeArgentinePeso CurrencyNameType = "Argentine Peso"

	CurrencyNameTypeArmenianDram CurrencyNameType = "Armenian Dram"

	CurrencyNameTypeArubanGuilder CurrencyNameType = "Aruban Guilder"

	CurrencyNameTypeAustralianDollar CurrencyNameType = "Australian Dollar"

	CurrencyNameTypeAustrianSchilling CurrencyNameType = "Austrian Schilling"

	CurrencyNameTypeAzerbaijanianManat CurrencyNameType = "Azerbaijanian Manat"

	CurrencyNameTypeBahamianDollar CurrencyNameType = "Bahamian Dollar"

	CurrencyNameTypeBahrainiDinar CurrencyNameType = "Bahraini Dinar"

	CurrencyNameTypeBangladeshTaka CurrencyNameType = "BangladeshTaka"

	CurrencyNameTypeBarbadosDollar CurrencyNameType = "Barbados Dollar"

	CurrencyNameTypeBelarussianRuble CurrencyNameType = "Belarussian Ruble"

	CurrencyNameTypeBelgianFranc CurrencyNameType = "Belgian Franc"

	CurrencyNameTypeBelizeDollar CurrencyNameType = "Belize Dollar"

	CurrencyNameTypeBermudianDollar CurrencyNameType = "Bermudian Dollar"

	CurrencyNameTypeBhutanNgultrum CurrencyNameType = "Bhutan Ngultrum"

	CurrencyNameTypeBoliviaBoliviano CurrencyNameType = "Bolivia Boliviano"

	CurrencyNameTypeBosniaConvertibleMark CurrencyNameType = "Bosnia Convertible Mark"

	CurrencyNameTypeBotswanaPula CurrencyNameType = "Botswana Pula"

	CurrencyNameTypeBrazilianReal CurrencyNameType = "Brazilian Real"

	CurrencyNameTypeBruneiDollar CurrencyNameType = "Brunei Dollar"

	CurrencyNameTypeBulgariaLev CurrencyNameType = "Bulgaria Lev"

	CurrencyNameTypeBurundiFranc CurrencyNameType = "Burundi Franc"

	CurrencyNameTypeCambodiaRiel CurrencyNameType = "Cambodia Riel"

	CurrencyNameTypeCanadianDollar CurrencyNameType = "Canadian Dollar"

	CurrencyNameTypeCapeVerdeEscudo CurrencyNameType = "Cape Verde Escudo"

	CurrencyNameTypeCaymanIslandsDollar CurrencyNameType = "Cayman Islands Dollar"

	CurrencyNameTypeCFAFrancBCEAO CurrencyNameType = "CFA Franc BCEAO"

	CurrencyNameTypeCFAFrancBEAC CurrencyNameType = "CFA Franc BEAC"

	CurrencyNameTypeCFPFranc CurrencyNameType = "CFP Franc"

	CurrencyNameTypeChileanPeso CurrencyNameType = "Chilean Peso"

	CurrencyNameTypeChineseYuanRenminbi CurrencyNameType = "Chinese Yuan Renminbi"

	CurrencyNameTypeColumbianPeso CurrencyNameType = "Columbian Peso"

	CurrencyNameTypeComoroFranc CurrencyNameType = "Comoro Franc"

	CurrencyNameTypeCongoFranc CurrencyNameType = "Congo Franc"

	CurrencyNameTypeCostaRicanColon CurrencyNameType = "Costa Rican Colon"

	CurrencyNameTypeCroatianKuna CurrencyNameType = "Croatian Kuna"

	CurrencyNameTypeCubanPeso CurrencyNameType = "Cuban Peso"

	CurrencyNameTypeCyprusPound CurrencyNameType = "Cyprus Pound"

	CurrencyNameTypeCzechKoruna CurrencyNameType = "Czech Koruna"

	CurrencyNameTypeDanishKrone CurrencyNameType = "Danish Krone"

	CurrencyNameTypeDeutscheMark CurrencyNameType = "Deutsche Mark"

	CurrencyNameTypeDijiboutiFranc CurrencyNameType = "Dijibouti Franc"

	CurrencyNameTypeDominicanPeso CurrencyNameType = "Dominican Peso"

	CurrencyNameTypeDutchGuilder CurrencyNameType = "Dutch Guilder"

	CurrencyNameTypeEastCaribbeanDollar CurrencyNameType = "East Caribbean Dollar"

	CurrencyNameTypeEcuadorSucre CurrencyNameType = "Ecuador Sucre"

	CurrencyNameTypeEgyptianPound CurrencyNameType = "Egyptian  Pound"

	CurrencyNameTypeElSalvadorianColon CurrencyNameType = "El Salvadorian Colon"

	CurrencyNameTypeEritreaNakfa CurrencyNameType = "Eritrea Nakfa"

	CurrencyNameTypeEscudoCaboverdiano CurrencyNameType = "Escudo Caboverdiano"

	CurrencyNameTypeEstoniaKroon CurrencyNameType = "Estonia Kroon"

	CurrencyNameTypeEthiopiaBirr CurrencyNameType = "Ethiopia Birr"

	CurrencyNameTypeEuro CurrencyNameType = "Euro"

	CurrencyNameTypeFalklandPound CurrencyNameType = "Falkland Pound"

	CurrencyNameTypeFijiDollar CurrencyNameType = "Fiji Dollar"

	CurrencyNameTypeFinnishMarkka CurrencyNameType = "Finnish Markka"

	CurrencyNameTypeFrenchFranc CurrencyNameType = "French Franc"

	CurrencyNameTypeGambiaDalasi CurrencyNameType = "Gambia Dalasi"

	CurrencyNameTypeGeorgiaLari CurrencyNameType = "Georgia Lari"

	CurrencyNameTypeGhanaCedi CurrencyNameType = "Ghana Cedi"

	CurrencyNameTypeGibraltarPound CurrencyNameType = "Gibraltar Pound"

	CurrencyNameTypeGreekDrachma CurrencyNameType = "Greek Drachma"

	CurrencyNameTypeGuatemalaQuetzal CurrencyNameType = "Guatemala Quetzal"

	CurrencyNameTypeGuyanaDollar CurrencyNameType = "Guyana Dollar"

	CurrencyNameTypeHaitiGourde CurrencyNameType = "Haiti Gourde"

	CurrencyNameTypeHondurasLempira CurrencyNameType = "Honduras Lempira"

	CurrencyNameTypeHongKongDollar CurrencyNameType = "Hong Kong Dollar"

	CurrencyNameTypeHungaryForint CurrencyNameType = "Hungary Forint"

	CurrencyNameTypeIcelandicKrona CurrencyNameType = "Icelandic Krona"

	CurrencyNameTypeIndianRupee CurrencyNameType = "Indian Rupee"

	CurrencyNameTypeIndonesiaRupiah CurrencyNameType = "Indonesia Rupiah"

	CurrencyNameTypeIranianRiyal CurrencyNameType = "Iranian Riyal"

	CurrencyNameTypeIraqiDinar CurrencyNameType = "Iraqi Dinar"

	CurrencyNameTypeIrishPunt CurrencyNameType = "Irish Punt"

	CurrencyNameTypeIsraelShekel CurrencyNameType = "Israel Shekel"

	CurrencyNameTypeItalianLira CurrencyNameType = "Italian Lira"

	CurrencyNameTypeJamaicanDollar CurrencyNameType = "Jamaican Dollar"

	CurrencyNameTypeJapaneseYen CurrencyNameType = "Japanese Yen"

	CurrencyNameTypeJordanianDinar CurrencyNameType = "Jordanian Dinar"

	CurrencyNameTypeKazakhstanTenge CurrencyNameType = "Kazakhstan Tenge"

	CurrencyNameTypeKenyanShilling CurrencyNameType = "Kenyan Shilling"

	CurrencyNameTypeKuwaitiDinar CurrencyNameType = "Kuwaiti Dinar"

	CurrencyNameTypeKyrgyzstanSom CurrencyNameType = "Kyrgyzstan Som"

	CurrencyNameTypeLaosKip CurrencyNameType = "Laos Kip"

	CurrencyNameTypeLatviaLat CurrencyNameType = "Latvia Lat"

	CurrencyNameTypeLebanesePound CurrencyNameType = "Lebanese Pound"

	CurrencyNameTypeLesothoMaloti CurrencyNameType = "Lesotho Maloti"

	CurrencyNameTypeLiberianDollar CurrencyNameType = "Liberian Dollar"

	CurrencyNameTypeLibyanDinar CurrencyNameType = "Libyan Dinar"

	CurrencyNameTypeLithuaniaLitas CurrencyNameType = "Lithuania Litas"

	CurrencyNameTypeLuxembourgFranc CurrencyNameType = "Luxembourg Franc"

	CurrencyNameTypeMacaoPataca CurrencyNameType = "Macao Pataca"

	CurrencyNameTypeMacedonianDenar CurrencyNameType = "Macedonian Denar"

	CurrencyNameTypeMalagasyFranc CurrencyNameType = "Malagasy Franc"

	CurrencyNameTypeMalawianKwacha CurrencyNameType = "Malawian Kwacha"

	CurrencyNameTypeMalaysianRinggit CurrencyNameType = "Malaysian Ringgit"

	CurrencyNameTypeMaldivesRufiyaa CurrencyNameType = "Maldives Rufiyaa"

	CurrencyNameTypeMalteseLira CurrencyNameType = "Maltese Lira"

	CurrencyNameTypeMauritaniaOuguiya CurrencyNameType = "Mauritania Ouguiya"

	CurrencyNameTypeMauritiusRupee CurrencyNameType = "Mauritius Rupee"

	CurrencyNameTypeMexicanPeso CurrencyNameType = "Mexican Peso"

	CurrencyNameTypeMoldovianLeu CurrencyNameType = "Moldovian Leu"

	CurrencyNameTypeMongoliaTugrik CurrencyNameType = "Mongolia Tugrik"

	CurrencyNameTypeMoroccanDirham CurrencyNameType = "Moroccan Dirham"

	CurrencyNameTypeMozambiqueMetical CurrencyNameType = "Mozambique Metical"

	CurrencyNameTypeMyanmarKyat CurrencyNameType = "Myanmar Kyat"

	CurrencyNameTypeNamibianDollar CurrencyNameType = "Namibian Dollar"

	CurrencyNameTypeNepaleseRupee CurrencyNameType = "Nepalese Rupee"

	CurrencyNameTypeNetherlandsAntillesGuilder CurrencyNameType = "Netherlands Antilles Guilder"

	CurrencyNameTypeNewZaire CurrencyNameType = "New Zaire"

	CurrencyNameTypeNewZealandDollar CurrencyNameType = "New Zealand Dollar"

	CurrencyNameTypeNicaraguaCordoba CurrencyNameType = "Nicaragua Cordoba"

	CurrencyNameTypeNigeriaNaira CurrencyNameType = "Nigeria Naira"

	CurrencyNameTypeNorthKoreanWon CurrencyNameType = "North Korean Won"

	CurrencyNameTypeNorwegianKrone CurrencyNameType = "Norwegian Krone"

	CurrencyNameTypePakistaniRupee CurrencyNameType = "Pakistani Rupee"

	CurrencyNameTypePanamaBalboa CurrencyNameType = "Panama Balboa"

	CurrencyNameTypePapuaNewGuineaKina CurrencyNameType = "Papua New Guinea Kina"

	CurrencyNameTypeParaguayGuarani CurrencyNameType = "Paraguay Guarani"

	CurrencyNameTypePeruNewSol CurrencyNameType = "Peru New Sol"

	CurrencyNameTypePhilippinePeso CurrencyNameType = "Philippine Peso"

	CurrencyNameTypePolandNewZloty CurrencyNameType = "Poland New Zloty"

	CurrencyNameTypePortugueseEscudo CurrencyNameType = "Portuguese Escudo"

	CurrencyNameTypeQatariRiyal CurrencyNameType = "Qatari Riyal"

	CurrencyNameTypeRiyalOmani CurrencyNameType = "Riyal Omani"

	CurrencyNameTypeRomanianLeu CurrencyNameType = "Romanian Leu"

	CurrencyNameTypeRussianFederationRouble CurrencyNameType = "Russian Federation Rouble"

	CurrencyNameTypeRwandaFranc CurrencyNameType = "Rwanda Franc"

	CurrencyNameTypeSaoTomeandPrincipeDobra CurrencyNameType = "Sao Tome and Principe Dobra"

	CurrencyNameTypeSaudiRiyal CurrencyNameType = "Saudi Riyal"

	CurrencyNameTypeSeychellesRupee CurrencyNameType = "Seychelles Rupee"

	CurrencyNameTypeSierraLeoneLeone CurrencyNameType = "Sierra Leone Leone"

	CurrencyNameTypeSingaporeDollar CurrencyNameType = "Singapore Dollar"

	CurrencyNameTypeSlovakDoruna CurrencyNameType = "Slovak Doruna"

	CurrencyNameTypeSloveniaTolar CurrencyNameType = "Slovenia Tolar"

	CurrencyNameTypeSolomanIslandsDollar CurrencyNameType = "Soloman Islands Dollar"

	CurrencyNameTypeSomaliaShilling CurrencyNameType = "Somalia Shilling"

	CurrencyNameTypeSouthAfricanRand CurrencyNameType = "South African Rand"

	CurrencyNameTypeSouthKoereanWon CurrencyNameType = "South Koerean Won"

	CurrencyNameTypeSpanishPeseta CurrencyNameType = "Spanish Peseta"

	CurrencyNameTypeSriLankanRupee CurrencyNameType = "Sri Lankan Rupee"

	CurrencyNameTypeStHelenaPound CurrencyNameType = "St Helena Pound"

	CurrencyNameTypeSterling CurrencyNameType = "Sterling"

	CurrencyNameTypeSudanesePound CurrencyNameType = "Sudanese Pound"

	CurrencyNameTypeSurinamGuilder CurrencyNameType = "Surinam Guilder"

	CurrencyNameTypeSwazilandLilangeni CurrencyNameType = "Swaziland Lilangeni"

	CurrencyNameTypeSwedishKrona CurrencyNameType = "Swedish Krona"

	CurrencyNameTypeSwissFranc CurrencyNameType = "Swiss Franc"

	CurrencyNameTypeSyrianPound CurrencyNameType = "Syrian Pound"

	CurrencyNameTypeTaiwaneseNTDollar CurrencyNameType = "Taiwanese NT Dollar"

	CurrencyNameTypeTajikistanRuble CurrencyNameType = "Tajikistan Ruble"

	CurrencyNameTypeTanzanianShilling CurrencyNameType = "Tanzanian Shilling"

	CurrencyNameTypeThailandBaht CurrencyNameType = "Thailand Baht"

	CurrencyNameTypeTimorEscudo CurrencyNameType = "Timor Escudo"

	CurrencyNameTypeTongaPalanga CurrencyNameType = "Tonga Palanga"

	CurrencyNameTypeTrinidadandTobagoDollar CurrencyNameType = "Trinidad and Tobago Dollar"

	CurrencyNameTypeTunasiaTunisianDinar CurrencyNameType = "Tunasia Tunisian Dinar"

	CurrencyNameTypeTurkishLira CurrencyNameType = "Turkish Lira"

	CurrencyNameTypeTurkmenistanManat CurrencyNameType = "Turkmenistan Manat"

	CurrencyNameTypeUAEDirham CurrencyNameType = "UAE Dirham"

	CurrencyNameTypeUgandianShilling CurrencyNameType = "Ugandian Shilling"

	CurrencyNameTypeUkraineHryvna CurrencyNameType = "Ukraine Hryvna"

	CurrencyNameTypeUruguayanNewPeso CurrencyNameType = "Uruguayan New Peso"

	CurrencyNameTypeUnitedStatesofAmericaDollar CurrencyNameType = "United States of America Dollar"

	CurrencyNameTypeUzbekistaniSum CurrencyNameType = "Uzbekistani Sum"

	CurrencyNameTypeVanuatuVatu CurrencyNameType = "Vanuatu Vatu"

	CurrencyNameTypeVenezuelaBolivar CurrencyNameType = "Venezuela Bolivar"

	CurrencyNameTypeVietnamDong CurrencyNameType = "Vietnam Dong"

	CurrencyNameTypeWesternSomoaTala CurrencyNameType = "Western Somoa Tala"

	CurrencyNameTypeYemenRiyal CurrencyNameType = "Yemen Riyal"

	CurrencyNameTypeYugoslaviaNewDinar CurrencyNameType = "Yugoslavia New Dinar"

	CurrencyNameTypeZambianKwacha CurrencyNameType = "Zambian Kwacha"

	CurrencyNameTypeZimbabweDollar CurrencyNameType = "Zimbabwe Dollar"
)

type CurrencyCodeType string

const (
	CurrencyCodeTypeAFA CurrencyCodeType = "AFA"

	CurrencyCodeTypeALL CurrencyCodeType = "ALL"

	CurrencyCodeTypeDZD CurrencyCodeType = "DZD"

	CurrencyCodeTypeAON CurrencyCodeType = "AON"

	CurrencyCodeTypeARS CurrencyCodeType = "ARS"

	CurrencyCodeTypeAMD CurrencyCodeType = "AMD"

	CurrencyCodeTypeAWG CurrencyCodeType = "AWG"

	CurrencyCodeTypeAUD CurrencyCodeType = "AUD"

	CurrencyCodeTypeATS CurrencyCodeType = "ATS"

	CurrencyCodeTypeAZM CurrencyCodeType = "AZM"

	CurrencyCodeTypeBSD CurrencyCodeType = "BSD"

	CurrencyCodeTypeBHD CurrencyCodeType = "BHD"

	CurrencyCodeTypeBDT CurrencyCodeType = "BDT"

	CurrencyCodeTypeBBD CurrencyCodeType = "BBD"

	CurrencyCodeTypeBYR CurrencyCodeType = "BYR"

	CurrencyCodeTypeBEF CurrencyCodeType = "BEF"

	CurrencyCodeTypeBZD CurrencyCodeType = "BZD"

	CurrencyCodeTypeBMD CurrencyCodeType = "BMD"

	CurrencyCodeTypeBTN CurrencyCodeType = "BTN"

	CurrencyCodeTypeBOB CurrencyCodeType = "BOB"

	CurrencyCodeTypeBAM CurrencyCodeType = "BAM"

	CurrencyCodeTypeBWP CurrencyCodeType = "BWP"

	CurrencyCodeTypeBRL CurrencyCodeType = "BRL"

	CurrencyCodeTypeBND CurrencyCodeType = "BND"

	CurrencyCodeTypeBGL CurrencyCodeType = "BGL"

	CurrencyCodeTypeBIF CurrencyCodeType = "BIF"

	CurrencyCodeTypeKHR CurrencyCodeType = "KHR"

	CurrencyCodeTypeCAD CurrencyCodeType = "CAD"

	CurrencyCodeTypeCVE CurrencyCodeType = "CVE"

	CurrencyCodeTypeKYD CurrencyCodeType = "KYD"

	CurrencyCodeTypeXOF CurrencyCodeType = "XOF"

	CurrencyCodeTypeXAF CurrencyCodeType = "XAF"

	CurrencyCodeTypeXPF CurrencyCodeType = "XPF"

	CurrencyCodeTypeCLP CurrencyCodeType = "CLP"

	CurrencyCodeTypeCNY CurrencyCodeType = "CNY"

	CurrencyCodeTypeCOP CurrencyCodeType = "COP"

	CurrencyCodeTypeKMF CurrencyCodeType = "KMF"

	CurrencyCodeTypeCDF CurrencyCodeType = "CDF"

	CurrencyCodeTypeCRC CurrencyCodeType = "CRC"

	CurrencyCodeTypeHRK CurrencyCodeType = "HRK"

	CurrencyCodeTypeCUP CurrencyCodeType = "CUP"

	CurrencyCodeTypeCYP CurrencyCodeType = "CYP"

	CurrencyCodeTypeCZK CurrencyCodeType = "CZK"

	CurrencyCodeTypeDKK CurrencyCodeType = "DKK"

	CurrencyCodeTypeDEM CurrencyCodeType = "DEM"

	CurrencyCodeTypeDJF CurrencyCodeType = "DJF"

	CurrencyCodeTypeDOP CurrencyCodeType = "DOP"

	CurrencyCodeTypeNLG CurrencyCodeType = "NLG"

	CurrencyCodeTypeXCD CurrencyCodeType = "XCD"

	CurrencyCodeTypeECS CurrencyCodeType = "ECS"

	CurrencyCodeTypeEGP CurrencyCodeType = "EGP"

	CurrencyCodeTypeSVC CurrencyCodeType = "SVC"

	CurrencyCodeTypeERN CurrencyCodeType = "ERN"

	CurrencyCodeTypeEEK CurrencyCodeType = "EEK"

	CurrencyCodeTypeETB CurrencyCodeType = "ETB"

	CurrencyCodeTypeEUR CurrencyCodeType = "EUR"

	CurrencyCodeTypeFKP CurrencyCodeType = "FKP"

	CurrencyCodeTypeFJD CurrencyCodeType = "FJD"

	CurrencyCodeTypeFIM CurrencyCodeType = "FIM"

	CurrencyCodeTypeFRF CurrencyCodeType = "FRF"

	CurrencyCodeTypeGMD CurrencyCodeType = "GMD"

	CurrencyCodeTypeGEL CurrencyCodeType = "GEL"

	CurrencyCodeTypeGHC CurrencyCodeType = "GHC"

	CurrencyCodeTypeGIP CurrencyCodeType = "GIP"

	CurrencyCodeTypeGRD CurrencyCodeType = "GRD"

	CurrencyCodeTypeGTQ CurrencyCodeType = "GTQ"

	CurrencyCodeTypeGYD CurrencyCodeType = "GYD"

	CurrencyCodeTypeHTG CurrencyCodeType = "HTG"

	CurrencyCodeTypeHNL CurrencyCodeType = "HNL"

	CurrencyCodeTypeHKD CurrencyCodeType = "HKD"

	CurrencyCodeTypeHUF CurrencyCodeType = "HUF"

	CurrencyCodeTypeISK CurrencyCodeType = "ISK"

	CurrencyCodeTypeINR CurrencyCodeType = "INR"

	CurrencyCodeTypeIDR CurrencyCodeType = "IDR"

	CurrencyCodeTypeIRR CurrencyCodeType = "IRR"

	CurrencyCodeTypeIQD CurrencyCodeType = "IQD"

	CurrencyCodeTypeIEP CurrencyCodeType = "IEP"

	CurrencyCodeTypeILS CurrencyCodeType = "ILS"

	CurrencyCodeTypeITL CurrencyCodeType = "ITL"

	CurrencyCodeTypeJMD CurrencyCodeType = "JMD"

	CurrencyCodeTypeJPY CurrencyCodeType = "JPY"

	CurrencyCodeTypeJOD CurrencyCodeType = "JOD"

	CurrencyCodeTypeKZT CurrencyCodeType = "KZT"

	CurrencyCodeTypeKES CurrencyCodeType = "KES"

	CurrencyCodeTypeKWD CurrencyCodeType = "KWD"

	CurrencyCodeTypeKGS CurrencyCodeType = "KGS"

	CurrencyCodeTypeLAK CurrencyCodeType = "LAK"

	CurrencyCodeTypeLVL CurrencyCodeType = "LVL"

	CurrencyCodeTypeLBP CurrencyCodeType = "LBP"

	CurrencyCodeTypeLSL CurrencyCodeType = "LSL"

	CurrencyCodeTypeLRD CurrencyCodeType = "LRD"

	CurrencyCodeTypeLYD CurrencyCodeType = "LYD"

	CurrencyCodeTypeLTL CurrencyCodeType = "LTL"

	CurrencyCodeTypeLUF CurrencyCodeType = "LUF"

	CurrencyCodeTypeMOP CurrencyCodeType = "MOP"

	CurrencyCodeTypeMKD CurrencyCodeType = "MKD"

	CurrencyCodeTypeMGF CurrencyCodeType = "MGF"

	CurrencyCodeTypeMWK CurrencyCodeType = "MWK"

	CurrencyCodeTypeMYR CurrencyCodeType = "MYR"

	CurrencyCodeTypeMVR CurrencyCodeType = "MVR"

	CurrencyCodeTypeMTL CurrencyCodeType = "MTL"

	CurrencyCodeTypeMRO CurrencyCodeType = "MRO"

	CurrencyCodeTypeMUR CurrencyCodeType = "MUR"

	CurrencyCodeTypeMXN CurrencyCodeType = "MXN"

	CurrencyCodeTypeMDL CurrencyCodeType = "MDL"

	CurrencyCodeTypeMNT CurrencyCodeType = "MNT"

	CurrencyCodeTypeMAD CurrencyCodeType = "MAD"

	CurrencyCodeTypeMZM CurrencyCodeType = "MZM"

	CurrencyCodeTypeMMK CurrencyCodeType = "MMK"

	CurrencyCodeTypeNAD CurrencyCodeType = "NAD"

	CurrencyCodeTypeNPR CurrencyCodeType = "NPR"

	CurrencyCodeTypeANG CurrencyCodeType = "ANG"

	CurrencyCodeTypeZRN CurrencyCodeType = "ZRN"

	CurrencyCodeTypeNZD CurrencyCodeType = "NZD"

	CurrencyCodeTypeNIC CurrencyCodeType = "NIC"

	CurrencyCodeTypeNGN CurrencyCodeType = "NGN"

	CurrencyCodeTypeKPW CurrencyCodeType = "KPW"

	CurrencyCodeTypeNOK CurrencyCodeType = "NOK"

	CurrencyCodeTypePKR CurrencyCodeType = "PKR"

	CurrencyCodeTypePAB CurrencyCodeType = "PAB"

	CurrencyCodeTypePGK CurrencyCodeType = "PGK"

	CurrencyCodeTypePYG CurrencyCodeType = "PYG"

	CurrencyCodeTypePEN CurrencyCodeType = "PEN"

	CurrencyCodeTypePHP CurrencyCodeType = "PHP"

	CurrencyCodeTypePLN CurrencyCodeType = "PLN"

	CurrencyCodeTypePTE CurrencyCodeType = "PTE"

	CurrencyCodeTypeQAR CurrencyCodeType = "QAR"

	CurrencyCodeTypeOMR CurrencyCodeType = "OMR"

	CurrencyCodeTypeROL CurrencyCodeType = "ROL"

	CurrencyCodeTypeRUR CurrencyCodeType = "RUR"

	CurrencyCodeTypeRWF CurrencyCodeType = "RWF"

	CurrencyCodeTypeSTD CurrencyCodeType = "STD"

	CurrencyCodeTypeSAR CurrencyCodeType = "SAR"

	CurrencyCodeTypeSCR CurrencyCodeType = "SCR"

	CurrencyCodeTypeSLL CurrencyCodeType = "SLL"

	CurrencyCodeTypeSGD CurrencyCodeType = "SGD"

	CurrencyCodeTypeSKK CurrencyCodeType = "SKK"

	CurrencyCodeTypeSIT CurrencyCodeType = "SIT"

	CurrencyCodeTypeSBD CurrencyCodeType = "SBD"

	CurrencyCodeTypeSOS CurrencyCodeType = "SOS"

	CurrencyCodeTypeZAR CurrencyCodeType = "ZAR"

	CurrencyCodeTypeKRW CurrencyCodeType = "KRW"

	CurrencyCodeTypeESP CurrencyCodeType = "ESP"

	CurrencyCodeTypeLKR CurrencyCodeType = "LKR"

	CurrencyCodeTypeSHP CurrencyCodeType = "SHP"

	CurrencyCodeTypeGBP CurrencyCodeType = "GBP"

	CurrencyCodeTypeSDP CurrencyCodeType = "SDP"

	CurrencyCodeTypeSRG CurrencyCodeType = "SRG"

	CurrencyCodeTypeSZL CurrencyCodeType = "SZL"

	CurrencyCodeTypeSEK CurrencyCodeType = "SEK"

	CurrencyCodeTypeCHF CurrencyCodeType = "CHF"

	CurrencyCodeTypeSYP CurrencyCodeType = "SYP"

	CurrencyCodeTypeTWD CurrencyCodeType = "TWD"

	CurrencyCodeTypeTJR CurrencyCodeType = "TJR"

	CurrencyCodeTypeTZS CurrencyCodeType = "TZS"

	CurrencyCodeTypeTHB CurrencyCodeType = "THB"

	CurrencyCodeTypeTPE CurrencyCodeType = "TPE"

	CurrencyCodeTypeTOP CurrencyCodeType = "TOP"

	CurrencyCodeTypeTTD CurrencyCodeType = "TTD"

	CurrencyCodeTypeTND CurrencyCodeType = "TND"

	CurrencyCodeTypeTRL CurrencyCodeType = "TRL"

	CurrencyCodeTypeTMM CurrencyCodeType = "TMM"

	CurrencyCodeTypeAED CurrencyCodeType = "AED"

	CurrencyCodeTypeUGX CurrencyCodeType = "UGX"

	CurrencyCodeTypeUAH CurrencyCodeType = "UAH"

	CurrencyCodeTypeUYU CurrencyCodeType = "UYU"

	CurrencyCodeTypeUSD CurrencyCodeType = "USD"

	CurrencyCodeTypeUZS CurrencyCodeType = "UZS"

	CurrencyCodeTypeVUV CurrencyCodeType = "VUV"

	CurrencyCodeTypeVEB CurrencyCodeType = "VEB"

	CurrencyCodeTypeVND CurrencyCodeType = "VND"

	CurrencyCodeTypeWST CurrencyCodeType = "WST"

	CurrencyCodeTypeYER CurrencyCodeType = "YER"

	CurrencyCodeTypeYUM CurrencyCodeType = "YUM"

	CurrencyCodeTypeZMK CurrencyCodeType = "ZMK"

	CurrencyCodeTypeZWD CurrencyCodeType = "ZWD"
)

type CurrencyNumberType string

const (
	CurrencyNumberType004 CurrencyNumberType = "004"

	CurrencyNumberType008 CurrencyNumberType = "008"

	CurrencyNumberType012 CurrencyNumberType = "012"

	CurrencyNumberType024 CurrencyNumberType = "024"

	CurrencyNumberType032 CurrencyNumberType = "032"

	CurrencyNumberType051 CurrencyNumberType = "051"

	CurrencyNumberType533 CurrencyNumberType = "533"

	CurrencyNumberType036 CurrencyNumberType = "036"

	CurrencyNumberType040 CurrencyNumberType = "040"

	CurrencyNumberType031 CurrencyNumberType = "031"

	CurrencyNumberType044 CurrencyNumberType = "044"

	CurrencyNumberType048 CurrencyNumberType = "048"

	CurrencyNumberType050 CurrencyNumberType = "050"

	CurrencyNumberType052 CurrencyNumberType = "052"

	CurrencyNumberType974 CurrencyNumberType = "974"

	CurrencyNumberType056 CurrencyNumberType = "056"

	CurrencyNumberType084 CurrencyNumberType = "084"

	CurrencyNumberType060 CurrencyNumberType = "060"

	CurrencyNumberType064 CurrencyNumberType = "064"

	CurrencyNumberType068 CurrencyNumberType = "068"

	CurrencyNumberType977 CurrencyNumberType = "977"

	CurrencyNumberType072 CurrencyNumberType = "072"

	CurrencyNumberType986 CurrencyNumberType = "986"

	CurrencyNumberType096 CurrencyNumberType = "096"

	CurrencyNumberType100 CurrencyNumberType = "100"

	CurrencyNumberType108 CurrencyNumberType = "108"

	CurrencyNumberType116 CurrencyNumberType = "116"

	CurrencyNumberType124 CurrencyNumberType = "124"

	CurrencyNumberType132 CurrencyNumberType = "132"

	CurrencyNumberType136 CurrencyNumberType = "136"

	CurrencyNumberType952 CurrencyNumberType = "952"

	CurrencyNumberType950 CurrencyNumberType = "950"

	CurrencyNumberType953 CurrencyNumberType = "953"

	CurrencyNumberType152 CurrencyNumberType = "152"

	CurrencyNumberType156 CurrencyNumberType = "156"

	CurrencyNumberType170 CurrencyNumberType = "170"

	CurrencyNumberType174 CurrencyNumberType = "174"

	CurrencyNumberType976 CurrencyNumberType = "976"

	CurrencyNumberType188 CurrencyNumberType = "188"

	CurrencyNumberType191 CurrencyNumberType = "191"

	CurrencyNumberType192 CurrencyNumberType = "192"

	CurrencyNumberType196 CurrencyNumberType = "196"

	CurrencyNumberType203 CurrencyNumberType = "203"

	CurrencyNumberType208 CurrencyNumberType = "208"

	CurrencyNumberType276 CurrencyNumberType = "276"

	CurrencyNumberType262 CurrencyNumberType = "262"

	CurrencyNumberType214 CurrencyNumberType = "214"

	CurrencyNumberType528 CurrencyNumberType = "528"

	CurrencyNumberType951 CurrencyNumberType = "951"

	CurrencyNumberType218 CurrencyNumberType = "218"

	CurrencyNumberType818 CurrencyNumberType = "818"

	CurrencyNumberType222 CurrencyNumberType = "222"

	CurrencyNumberType232 CurrencyNumberType = "232"

	CurrencyNumberType233 CurrencyNumberType = "233"

	CurrencyNumberType230 CurrencyNumberType = "230"

	CurrencyNumberType978 CurrencyNumberType = "978"

	CurrencyNumberType238 CurrencyNumberType = "238"

	CurrencyNumberType242 CurrencyNumberType = "242"

	CurrencyNumberType246 CurrencyNumberType = "246"

	CurrencyNumberType250 CurrencyNumberType = "250"

	CurrencyNumberType270 CurrencyNumberType = "270"

	CurrencyNumberType268 CurrencyNumberType = "268"

	CurrencyNumberType288 CurrencyNumberType = "288"

	CurrencyNumberType292 CurrencyNumberType = "292"

	CurrencyNumberType300 CurrencyNumberType = "300"

	CurrencyNumberType320 CurrencyNumberType = "320"

	CurrencyNumberType328 CurrencyNumberType = "328"

	CurrencyNumberType332 CurrencyNumberType = "332"

	CurrencyNumberType340 CurrencyNumberType = "340"

	CurrencyNumberType344 CurrencyNumberType = "344"

	CurrencyNumberType348 CurrencyNumberType = "348"

	CurrencyNumberType352 CurrencyNumberType = "352"

	CurrencyNumberType356 CurrencyNumberType = "356"

	CurrencyNumberType360 CurrencyNumberType = "360"

	CurrencyNumberType364 CurrencyNumberType = "364"

	CurrencyNumberType368 CurrencyNumberType = "368"

	CurrencyNumberType372 CurrencyNumberType = "372"

	CurrencyNumberType376 CurrencyNumberType = "376"

	CurrencyNumberType380 CurrencyNumberType = "380"

	CurrencyNumberType388 CurrencyNumberType = "388"

	CurrencyNumberType392 CurrencyNumberType = "392"

	CurrencyNumberType400 CurrencyNumberType = "400"

	CurrencyNumberType398 CurrencyNumberType = "398"

	CurrencyNumberType404 CurrencyNumberType = "404"

	CurrencyNumberType414 CurrencyNumberType = "414"

	CurrencyNumberType417 CurrencyNumberType = "417"

	CurrencyNumberType418 CurrencyNumberType = "418"

	CurrencyNumberType428 CurrencyNumberType = "428"

	CurrencyNumberType422 CurrencyNumberType = "422"

	CurrencyNumberType426 CurrencyNumberType = "426"

	CurrencyNumberType430 CurrencyNumberType = "430"

	CurrencyNumberType434 CurrencyNumberType = "434"

	CurrencyNumberType440 CurrencyNumberType = "440"

	CurrencyNumberType442 CurrencyNumberType = "442"

	CurrencyNumberType446 CurrencyNumberType = "446"

	CurrencyNumberType807 CurrencyNumberType = "807"

	CurrencyNumberType450 CurrencyNumberType = "450"

	CurrencyNumberType454 CurrencyNumberType = "454"

	CurrencyNumberType458 CurrencyNumberType = "458"

	CurrencyNumberType462 CurrencyNumberType = "462"

	CurrencyNumberType470 CurrencyNumberType = "470"

	CurrencyNumberType478 CurrencyNumberType = "478"

	CurrencyNumberType480 CurrencyNumberType = "480"

	CurrencyNumberType484 CurrencyNumberType = "484"

	CurrencyNumberType498 CurrencyNumberType = "498"

	CurrencyNumberType496 CurrencyNumberType = "496"

	CurrencyNumberType504 CurrencyNumberType = "504"

	CurrencyNumberType508 CurrencyNumberType = "508"

	CurrencyNumberType104 CurrencyNumberType = "104"

	CurrencyNumberType516 CurrencyNumberType = "516"

	CurrencyNumberType524 CurrencyNumberType = "524"

	CurrencyNumberType532 CurrencyNumberType = "532"

	CurrencyNumberType186 CurrencyNumberType = "186"

	CurrencyNumberType554 CurrencyNumberType = "554"

	CurrencyNumberType558 CurrencyNumberType = "558"

	CurrencyNumberType566 CurrencyNumberType = "566"

	CurrencyNumberType408 CurrencyNumberType = "408"

	CurrencyNumberType578 CurrencyNumberType = "578"

	CurrencyNumberType586 CurrencyNumberType = "586"

	CurrencyNumberType590 CurrencyNumberType = "590"

	CurrencyNumberType598 CurrencyNumberType = "598"

	CurrencyNumberType600 CurrencyNumberType = "600"

	CurrencyNumberType604 CurrencyNumberType = "604"

	CurrencyNumberType608 CurrencyNumberType = "608"

	CurrencyNumberType985 CurrencyNumberType = "985"

	CurrencyNumberType620 CurrencyNumberType = "620"

	CurrencyNumberType634 CurrencyNumberType = "634"

	CurrencyNumberType512 CurrencyNumberType = "512"

	CurrencyNumberType642 CurrencyNumberType = "642"

	CurrencyNumberType810 CurrencyNumberType = "810"

	CurrencyNumberType646 CurrencyNumberType = "646"

	CurrencyNumberType678 CurrencyNumberType = "678"

	CurrencyNumberType682 CurrencyNumberType = "682"

	CurrencyNumberType690 CurrencyNumberType = "690"

	CurrencyNumberType694 CurrencyNumberType = "694"

	CurrencyNumberType702 CurrencyNumberType = "702"

	CurrencyNumberType703 CurrencyNumberType = "703"

	CurrencyNumberType705 CurrencyNumberType = "705"

	CurrencyNumberType090 CurrencyNumberType = "090"

	CurrencyNumberType706 CurrencyNumberType = "706"

	CurrencyNumberType710 CurrencyNumberType = "710"

	CurrencyNumberType410 CurrencyNumberType = "410"

	CurrencyNumberType724 CurrencyNumberType = "724"

	CurrencyNumberType144 CurrencyNumberType = "144"

	CurrencyNumberType654 CurrencyNumberType = "654"

	CurrencyNumberType826 CurrencyNumberType = "826"

	CurrencyNumberType736 CurrencyNumberType = "736"

	CurrencyNumberType740 CurrencyNumberType = "740"

	CurrencyNumberType748 CurrencyNumberType = "748"

	CurrencyNumberType752 CurrencyNumberType = "752"

	CurrencyNumberType756 CurrencyNumberType = "756"

	CurrencyNumberType760 CurrencyNumberType = "760"

	CurrencyNumberType901 CurrencyNumberType = "901"

	CurrencyNumberType762 CurrencyNumberType = "762"

	CurrencyNumberType834 CurrencyNumberType = "834"

	CurrencyNumberType764 CurrencyNumberType = "764"

	CurrencyNumberType626 CurrencyNumberType = "626"

	CurrencyNumberType776 CurrencyNumberType = "776"

	CurrencyNumberType780 CurrencyNumberType = "780"

	CurrencyNumberType788 CurrencyNumberType = "788"

	CurrencyNumberType792 CurrencyNumberType = "792"

	CurrencyNumberType795 CurrencyNumberType = "795"

	CurrencyNumberType784 CurrencyNumberType = "784"

	CurrencyNumberType800 CurrencyNumberType = "800"

	CurrencyNumberType980 CurrencyNumberType = "980"

	CurrencyNumberType858 CurrencyNumberType = "858"

	CurrencyNumberType840 CurrencyNumberType = "840"

	CurrencyNumberType860 CurrencyNumberType = "860"

	CurrencyNumberType548 CurrencyNumberType = "548"

	CurrencyNumberType862 CurrencyNumberType = "862"

	CurrencyNumberType704 CurrencyNumberType = "704"

	CurrencyNumberType882 CurrencyNumberType = "882"

	CurrencyNumberType886 CurrencyNumberType = "886"

	CurrencyNumberType891 CurrencyNumberType = "891"

	CurrencyNumberType894 CurrencyNumberType = "894"

	CurrencyNumberType716 CurrencyNumberType = "716"
)

type SpecificationTypeEnum string

const (
	SpecificationTypeEnumLength SpecificationTypeEnum = "Length"

	SpecificationTypeEnumThickness SpecificationTypeEnum = "Thickness"

	SpecificationTypeEnumRadius SpecificationTypeEnum = "Radius"

	SpecificationTypeEnumVolume SpecificationTypeEnum = "Volume"

	SpecificationTypeEnumCapacity SpecificationTypeEnum = "Capacity"

	SpecificationTypeEnumMemory SpecificationTypeEnum = "Memory"

	SpecificationTypeEnumDataPorts SpecificationTypeEnum = "Data Ports"

	SpecificationTypeEnumCapacitance SpecificationTypeEnum = "Capacitance"

	SpecificationTypeEnumVoltage SpecificationTypeEnum = "Voltage"

	SpecificationTypeEnumPointSize SpecificationTypeEnum = "Point Size"

	SpecificationTypeEnumSheetSize SpecificationTypeEnum = "Sheet Size"

	SpecificationTypeEnumSheetCount SpecificationTypeEnum = "Sheet Count"

	SpecificationTypeEnumPockets SpecificationTypeEnum = "Pockets"

	SpecificationTypeEnumInseam SpecificationTypeEnum = "Inseam"

	SpecificationTypeEnumBust SpecificationTypeEnum = "Bust"

	SpecificationTypeEnumChest SpecificationTypeEnum = "Chest"

	SpecificationTypeEnumWaist SpecificationTypeEnum = "Waist"

	SpecificationTypeEnumHips SpecificationTypeEnum = "Hips"

	SpecificationTypeEnumCup SpecificationTypeEnum = "Cup"

	SpecificationTypeEnumRise SpecificationTypeEnum = "Rise"

	SpecificationTypeEnumNeck SpecificationTypeEnum = "Neck"

	SpecificationTypeEnumThigh SpecificationTypeEnum = "Thigh"

	SpecificationTypeEnumShoulders SpecificationTypeEnum = "Shoulders"

	SpecificationTypeEnumSleeve SpecificationTypeEnum = "Sleeve"

	SpecificationTypeEnumDeviceSize SpecificationTypeEnum = "Device Size"
)

type ApparelStyleEnum string

const (
	ApparelStyleEnumUnisex ApparelStyleEnum = "Unisex"

	ApparelStyleEnumYouth ApparelStyleEnum = "Youth"

	ApparelStyleEnumGirls ApparelStyleEnum = "Girls"

	ApparelStyleEnumBoys ApparelStyleEnum = "Boys"

	ApparelStyleEnumWomens ApparelStyleEnum = "Womens"

	ApparelStyleEnumWomensTall ApparelStyleEnum = "WomensTall"

	ApparelStyleEnumMens ApparelStyleEnum = "Mens"

	ApparelStyleEnumMensTall ApparelStyleEnum = "MensTall"
)

type LabelSizeEnum string

const (
	LabelSizeEnumOSFA LabelSizeEnum = "OSFA"

	LabelSizeEnum6XS LabelSizeEnum = "6XS"

	LabelSizeEnum5XS LabelSizeEnum = "5XS"

	LabelSizeEnum4XS LabelSizeEnum = "4XS"

	LabelSizeEnum3XS LabelSizeEnum = "3XS"

	LabelSizeEnum2XS LabelSizeEnum = "2XS"

	LabelSizeEnumXS LabelSizeEnum = "XS"

	LabelSizeEnumS LabelSizeEnum = "S"

	LabelSizeEnumM LabelSizeEnum = "M"

	LabelSizeEnumL LabelSizeEnum = "L"

	LabelSizeEnumXL LabelSizeEnum = "XL"

	LabelSizeEnum2XL LabelSizeEnum = "2XL"

	LabelSizeEnum3XL LabelSizeEnum = "3XL"

	LabelSizeEnum4XL LabelSizeEnum = "4XL"

	LabelSizeEnum5XL LabelSizeEnum = "5XL"

	LabelSizeEnum6XL LabelSizeEnum = "6XL"

	LabelSizeEnumCUSTOM LabelSizeEnum = "CUSTOM"
)

type DimensionUomEnum string

const (
	DimensionUomEnumMM DimensionUomEnum = "MM"

	DimensionUomEnumCM DimensionUomEnum = "CM"

	DimensionUomEnumMR DimensionUomEnum = "MR"

	DimensionUomEnumIN DimensionUomEnum = "IN"

	DimensionUomEnumFT DimensionUomEnum = "FT"

	DimensionUomEnumYD DimensionUomEnum = "YD"
)

type WeightUomEnum string

const (
	WeightUomEnumME WeightUomEnum = "ME"

	WeightUomEnumKG WeightUomEnum = "KG"

	WeightUomEnumOZ WeightUomEnum = "OZ"

	WeightUomEnumLB WeightUomEnum = "LB"
)

type RelationTypeEnum string

const (
	RelationTypeEnumSubstitute RelationTypeEnum = "Substitute"

	RelationTypeEnumCompanionSell RelationTypeEnum = "Companion Sell"

	RelationTypeEnumCommonGrouping RelationTypeEnum = "Common Grouping"
)

type SeverityType string

const (
	SeverityTypeError SeverityType = "Error"

	SeverityTypeInformation SeverityType = "Information"

	SeverityTypeWarning SeverityType = "Warning"
)

type FobPointArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ FobPointArray" bson:"-"`

	FobPoint []*FobPoint `xml:"FobPoint,omitempty" json:"FobPoint,omitempty"`
}

type FobPoint struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ FobPoint" bson:"-"`

	FobId *FobId `xml:"fobId,omitempty" json:"fobId,omitempty"`

	FobCity string `xml:"fobCity,omitempty" json:"fobCity,omitempty"`

	FobState string `xml:"fobState,omitempty" json:"fobState,omitempty"`

	FobPostalCode *FobPostalCode `xml:"fobPostalCode,omitempty" json:"fobPostalCode,omitempty"`

	FobCountry string `xml:"fobCountry,omitempty" json:"fobCountry,omitempty"`
}

type Currency CurrencyCodeType

type ApparelSizeArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ApparelSizeArray" bson:"-"`

	ApparelSize []*ApparelSize `xml:"ApparelSize,omitempty" json:"ApparelSize,omitempty"`
}

type Dimension struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ Dimension" bson:"-"`

	DimensionUom *DimensionUom `xml:"dimensionUom,omitempty" json:"dimensionUom,omitempty"`

	Depth *Depth `xml:"depth,omitempty" json:"depth,omitempty"`

	Height *Height `xml:"height,omitempty" json:"height,omitempty"`

	Width *Width `xml:"width,omitempty" json:"width,omitempty"`

	WeightUom *WeightUom `xml:"weightUom,omitempty" json:"weightUom,omitempty"`

	Weight *Weight `xml:"weight,omitempty" json:"weight,omitempty"`
}

type ProductPackage struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductPackage" bson:"-"`

	Default_ bool `xml:"default,omitempty" json:"default,omitempty"`

	PackageType *PackageType `xml:"packageType,omitempty" json:"packageType,omitempty"`

	Description *Description `xml:"description,omitempty" json:"description,omitempty"`

	Quantity *Quantity `xml:"quantity,omitempty" json:"quantity,omitempty"`

	DimensionUom *DimensionUom `xml:"dimensionUom,omitempty" json:"dimensionUom,omitempty"`

	Depth *Depth `xml:"depth,omitempty" json:"depth,omitempty"`

	Height *Height `xml:"height,omitempty" json:"height,omitempty"`

	Width *Width `xml:"width,omitempty" json:"width,omitempty"`

	WeightUom *WeightUom `xml:"weightUom,omitempty" json:"weightUom,omitempty"`

	Weight *Weight `xml:"weight,omitempty" json:"weight,omitempty"`
}

type ShippingPackage struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ShippingPackage" bson:"-"`

	PackageType *PackageType `xml:"packageType,omitempty" json:"packageType,omitempty"`

	Description *Description `xml:"description,omitempty" json:"description,omitempty"`

	Quantity *Quantity `xml:"quantity,omitempty" json:"quantity,omitempty"`

	DimensionUom *DimensionUom `xml:"dimensionUom,omitempty" json:"dimensionUom,omitempty"`

	Depth *Depth `xml:"depth,omitempty" json:"depth,omitempty"`

	Height *Height `xml:"height,omitempty" json:"height,omitempty"`

	Width *Width `xml:"width,omitempty" json:"width,omitempty"`

	WeightUom *WeightUom `xml:"weightUom,omitempty" json:"weightUom,omitempty"`

	Weight *Weight `xml:"weight,omitempty" json:"weight,omitempty"`
}

type Specification struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ Specification" bson:"-"`

	SpecificationType *SpecificationTypeEnum `xml:"specificationType,omitempty" json:"specificationType,omitempty"`

	SpecificationUom string `xml:"SpecificationUom,omitempty" json:"SpecificationUom,omitempty"`

	MeasurementValue string `xml:"measurementValue,omitempty" json:"measurementValue,omitempty"`
}

type ProductCategory struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductCategory" bson:"-"`

	Category string `xml:"category,omitempty" json:"category,omitempty"`

	SubCategory string `xml:"subCategory,omitempty" json:"subCategory,omitempty"`
}

type RelatedProduct struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ RelatedProduct" bson:"-"`

	RelationType *RelationTypeEnum `xml:"relationType,omitempty" json:"relationType,omitempty"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

	PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`
}

type ProductKeyword struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductKeyword" bson:"-"`

	Keyword string `xml:"keyword,omitempty" json:"keyword,omitempty"`
}

type ProductMarketingPoint struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductMarketingPoint" bson:"-"`

	PointType string `xml:"pointType,omitempty" json:"pointType,omitempty"`

	PointCopy string `xml:"pointCopy,omitempty" json:"pointCopy,omitempty"`
}

type ChangeTimeStamp time.Time

type ServiceMessageArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ServiceMessageArray" bson:"-"`

	ServiceMessage []*ServiceMessage `xml:"ServiceMessage,omitempty" json:"ServiceMessage,omitempty"`
}

type ServiceMessage struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ServiceMessage" bson:"-"`

	Code int32 `xml:"code,omitempty" json:"code,omitempty"`

	Description string `xml:"description,omitempty" json:"description,omitempty"`

	Severity *SeverityType `xml:"severity,omitempty" json:"severity,omitempty"`
}

// type PriceExpiresDate time.Time

// type EndDate time.Time

// type EffectiveDate time.Time

type IsCaution bool

type IsRushCharge bool

type SpecialPricingExcluded bool

type IsSellable bool

type IsCloseout bool

type Depth float64

type Height float64

type Weight float64

type Width float64

type Quantity float64

type ApparelSize struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ApparelSize" bson:"-"`

	ApparelStyle *ApparelStyleEnum `xml:"apparelStyle,omitempty" json:"apparelStyle,omitempty"`

	LabelSize *LabelSizeEnum `xml:"labelSize,omitempty" json:"labelSize,omitempty"`

	CustomSize string `xml:"customSize,omitempty" json:"customSize,omitempty"`
}

type SizeApparelArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ SizeApparelArray" bson:"-"`

	SizeApparel []struct {
		ApparelStyle *ApparelStyleEnum `xml:"apparelStyle,omitempty" json:"apparelStyle,omitempty"`

		LabelSize *LabelSizeEnum `xml:"labelSize,omitempty" json:"labelSize,omitempty"`
	} `xml:"SizeApparel,omitempty" json:"SizeApparel,omitempty"`
}

type TaxCategoryArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ TaxCategoryArray" bson:"-"`

	TaxCategory []struct {
	} `xml:"TaxCategory,omitempty" json:"TaxCategory,omitempty"`
}

type ImprintColorsArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ImprintColorsArray" bson:"-"`

	Color []struct {
	} `xml:"Color,omitempty" json:"Color,omitempty"`
}

type Color struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ Color" bson:"-"`

	StandardColorName string `xml:"standardColorName,omitempty" json:"standardColorName,omitempty"`

	Hex string `xml:"hex,omitempty" json:"hex,omitempty"`

	ApproximatePms string `xml:"approximatePms,omitempty" json:"approximatePms,omitempty"`

	ColorName string `xml:"colorName,omitempty" json:"colorName,omitempty"`
}

type NmfcCode float64

type IsOnDemand bool

type IsRushService bool

type ComplianceInfoAvailable bool

type IsHazmat bool

type QuantityLTM int32

type ProductPriceGroup struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductPriceGroup" bson:"-"`

	ProductPriceArray struct {
		ProductPrice []*ProductPrice `xml:"ProductPrice,omitempty" json:"ProductPrice,omitempty"`
	} `xml:"ProductPriceArray,omitempty" json:"ProductPriceArray,omitempty"`

	GroupName *GroupName `xml:"groupName,omitempty" json:"groupName,omitempty"`

	Currency *Currency `xml:"currency,omitempty" json:"currency,omitempty"`

	Description *Description `xml:"description,omitempty" json:"description,omitempty"`
}

type ProductPrice struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ ProductPrice" bson:"-"`

	QuantityMin int32 `xml:"quantityMin,omitempty" json:"quantityMin,omitempty"`

	QuantityMax int32 `xml:"quantityMax,omitempty" json:"quantityMax,omitempty"`

	Price float64 `xml:"price,omitempty" json:"price,omitempty"`

	DiscountCode string `xml:"discountCode,omitempty" json:"discountCode,omitempty"`
}

type LocationDecorationArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/SharedObjects/ LocationDecorationArray" bson:"-"`

	LocationDecoration []struct {
		LocationName string `xml:"locationName,omitempty" json:"locationName,omitempty"`

		MaxImprintColors int32 `xml:"maxImprintColors,omitempty" json:"maxImprintColors,omitempty"`

		DecorationName string `xml:"decorationName,omitempty" json:"decorationName,omitempty"`

		LocationDecorationComboDefault bool `xml:"locationDecorationComboDefault,omitempty" json:"locationDecorationComboDefault,omitempty"`

		PriceIncludes bool `xml:"priceIncludes,omitempty" json:"priceIncludes,omitempty"`
	} `xml:"LocationDecoration,omitempty" json:"LocationDecoration,omitempty"`
}

type GetProductRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductRequest" bson:"-"`

	WsVersion *WsVersion `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *Id `xml:"id,omitempty" json:"id,omitempty"`

	Password *Password `xml:"password,omitempty" json:"password,omitempty"`

	LocalizationCountry *LocalizationCountry `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *LocalizationLanguage `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

	PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`

	ColorName *ColorName `xml:"colorName,omitempty" json:"colorName,omitempty"`

	ApparelSizeArray *ApparelSizeArray `xml:"ApparelSizeArray,omitempty" json:"ApparelSizeArray,omitempty"`
}

type Product struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ Product" bson:"-"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty" bson:"product_id,omitempty"`

	ProductName *ProductName `xml:"productName,omitempty" json:"productName,omitempty" bson:"product_name,omitempty"`

	Description []*Description `xml:"description,omitempty" json:"description,omitempty" bson:"description,omitempty"`

	PriceExpiresDate *customTime `xml:"priceExpiresDate,omitempty" json:"priceExpiresDate,omitempty" bson:"price_expires_date,omitempty"`

	ProductMarketingPointArray struct {
		ProductMarketingPoint []*ProductMarketingPoint `xml:"ProductMarketingPoint,omitempty" json:"ProductMarketingPoint,omitempty" bson:"product_marketing_point,omitempty"`
	} `xml:"ProductMarketingPointArray,omitempty" json:"ProductMarketingPointArray,omitempty" bson:"product_marketing_point_array,omitempty"`

	ProductKeywordArray struct {
		ProductKeyword []*ProductKeyword `xml:"ProductKeyword,omitempty" json:"ProductKeyword,omitempty" bson:"product_keyword,omitempty"`
	} `xml:"ProductKeywordArray,omitempty" json:"ProductKeywordArray,omitempty" bson:"product_keyword_array,omitempty"`

	ProductBrand *ProductBrand `xml:"productBrand,omitempty" json:"productBrand,omitempty" bson:"product_brand,omitempty"`

	Export bool `xml:"export,omitempty" json:"export,omitempty" bson:"export,omitempty"`

	ProductCategoryArray struct {
		ProductCategory []*ProductCategory `xml:"ProductCategory,omitempty" json:"ProductCategory,omitempty" bson:"product_category,omitempty"`
	} `xml:"ProductCategoryArray,omitempty" json:"ProductCategoryArray,omitempty" bson:"product_category_array,omitempty"`

	RelatedProductArray struct {
		RelatedProduct []*RelatedProduct `xml:"RelatedProduct,omitempty" json:"RelatedProduct,omitempty" bson:"related_product,omitempty"`
	} `xml:"RelatedProductArray,omitempty" json:"RelatedProductArray,omitempty" bson:"related_product_array,omitempty"`

	PrimaryImageUrl *PrimaryImageUrl `xml:"primaryImageUrl,omitempty" json:"primaryImageUrl,omitempty" bson:"primary_image_url,omitempty"`

	ProductPriceGroupArray struct {
		ProductPriceGroup []*ProductPriceGroup `xml:"ProductPriceGroup,omitempty" json:"ProductPriceGroup,omitempty" bson:"product_price_group,omitempty"`
	} `xml:"ProductPriceGroupArray,omitempty" json:"ProductPriceGroupArray,omitempty" bson:"product_price_group_array,omitempty"`

	ComplianceInfoAvailable *ComplianceInfoAvailable `xml:"complianceInfoAvailable,omitempty" json:"complianceInfoAvailable,omitempty" bson:"compliance_info_available,omitempty"`

	UnspscCommodityCode int32 `xml:"unspscCommodityCode,omitempty" json:"unspscCommodityCode,omitempty" bson:"unspsc_commodity_code,omitempty"`

	LocationDecorationArray *LocationDecorationArray `xml:"LocationDecorationArray,omitempty" json:"LocationDecorationArray,omitempty" json:"location_decoration_array,omitempty"`

	ProductPartArray struct {
		ProductPart []struct {
			PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty" bson:"part_id,omitempty"`

			PrimaryColor struct {
				Color *Color `xml:"Color,omitempty" json:"Color,omitempty" bson:"color,omitempty"`
			} `xml:"primaryColor,omitempty" json:"primaryColor,omitempty" bson:"primary_color,omitempty"`

			Description []*Description `xml:"description,omitempty" json:"description,omitempty" bson:"description,omitempty"`

			CountryOfOrigin *CountryOfOrigin `xml:"countryOfOrigin,omitempty" json:"countryOfOrigin,omitempty" bson:"country_of_origin,omitempty"`

			ColorArray struct {
				Color []*Color `xml:"Color,omitempty" json:"Color,omitempty" bson:"color,omitempty"`
			} `xml:"ColorArray,omitempty" json:"ColorArray,omitempty" bson:"color_array,omitempty"`

			PrimaryMaterial *PrimaryMaterial `xml:"primaryMaterial,omitempty" json:"primaryMaterial,omitempty" json:"primary_material,omitempty"`

			SpecificationArray struct {
				Specification []*Specification `xml:"Specification,omitempty" json:"Specification,omitempty" bson:"specification,omitempty"`
			} `xml:"SpecificationArray,omitempty" json:"SpecificationArray,omitempty" bson:"specification_array,omitempty"`

			Shape *Shape `xml:"shape,omitempty" json:"shape,omitempty" bson:"shape,omitempty"`

			ApparelSize *ApparelSize `xml:"ApparelSize,omitempty" json:"ApparelSize,omitempty" bson:"apparel_size,omitempty"`

			Dimension *Dimension `xml:"Dimension,omitempty" json:"Dimension,omitempty" bson:"dimension,omitempty"`

			LeadTime int32 `xml:"leadTime,omitempty" json:"leadTime,omitempty" bson:"lead_time,omitempty"`

			Unspsc *Unspsc `xml:"unspsc,omitempty" json:"unspsc,omitempty" bson:"unspsc,omitempty"`

			Gtin *Gtin `xml:"gtin,omitempty" json:"gtin,omitempty" bson:"gtin,omitempty"`

			IsRushService *IsRushService `xml:"isRushService,omitempty" json:"isRushService,omitempty" bson:"is_rush_service,omitempty"`

			ProductPackagingArray struct {
				ProductPackage []*ProductPackage `xml:"ProductPackage,omitempty" json:"ProductPackage,omitempty" bson:"product_package,omitempty"`
			} `xml:"ProductPackagingArray,omitempty" json:"ProductPackagingArray,omitempty" bson:"product_packaging_array,omitempty"`

			ShippingPackageArray struct {
				ShippingPackage []*ShippingPackage `xml:"ShippingPackage,omitempty" json:"ShippingPackage,omitempty" bson:"shipping_package,omitempty"`
			} `xml:"ShippingPackageArray,omitempty" json:"ShippingPackageArray,omitempty" bson:"shipping_package_array,omitempty"`

			EndDate *customTime `xml:"endDate,omitempty" json:"endDate,omitempty" bson:"end_date,omitempty"`

			EffectiveDate *customTime `xml:"effectiveDate,omitempty" json:"effectiveDate,omitempty" bson:"effective_date,omitempty"`

			IsCloseout *IsCloseout `xml:"isCloseout,omitempty" json:"isCloseout,omitempty" bson:"is_closeout,omitempty"`

			IsCaution *IsCaution `xml:"isCaution,omitempty" json:"isCaution,omitempty" bson:"is_caution,omitempty"`

			CautionComment *CautionComment `xml:"cautionComment,omitempty" json:"cautionComment,omitempty" bson:"caution_comment,omitempty"`

			NmfcCode *NmfcCode `xml:"nmfcCode,omitempty" json:"nmfcCode,omitempty" bson:"nmfc_code,omitempty"`

			NmfcDescription *NmfcDescription `xml:"nmfcDescription,omitempty" json:"nmfcDescription,omitempty" bson:"nmfc_description,omitempty"`

			NmfcNumber *NmfcNumber `xml:"nmfcNumber,omitempty" json:"nmfcNumber,omitempty" bson:"nmfc_number,omitempty"`

			IsOnDemand *IsOnDemand `xml:"isOnDemand,omitempty" json:"isOnDemand,omitempty" bson:"is_on_demand,omitempty"`

			IsHazmat *IsHazmat `xml:"isHazmat,omitempty" json:"isHazmat,omitempty" bson:"is_hazmat,omitempty"`
		} `xml:"ProductPart,omitempty" json:"ProductPart,omitempty" bson:"product_part,omitempty"`
	} `xml:"ProductPartArray,omitempty" json:"ProductPartArray,omitempty" bson:"product_part_array,omitempty"`

	LastChangeDate *customTime `xml:"lastChangeDate,omitempty" json:"lastChangeDate,omitempty" bson:"last_change_date,omitempty"`

	CreationDate *customTime `xml:"creationDate,omitempty" json:"creationDate,omitempty" bson:"creation_date,omitempty"`

	EndDate *customTime `xml:"endDate,omitempty" json:"endDate,omitempty" bson:"end_date,omitempty"`

	EffectiveDate *customTime `xml:"effectiveDate,omitempty" json:"effectiveDate,omitempty" bson:"effective_date,omitempty"`

	IsCaution *IsCaution `xml:"isCaution,omitempty" json:"isCaution,omitempty" bson:"is_caution,omitempty"`

	CautionComment *CautionComment `xml:"cautionComment,omitempty" json:"cautionComment,omitempty" bson:"caution_comment,omitempty"`

	IsCloseout *IsCloseout `xml:"isCloseout,omitempty" json:"isCloseout,omitempty" bson:"is_closeout,omitempty"`

	LineName *LineName `xml:"lineName,omitempty" json:"lineName,omitempty" bson:"line_name,omitempty"`

	DefaultSetupCharge *DefaultSetupCharge `xml:"defaultSetupCharge,omitempty" json:"defaultSetupCharge,omitempty" bson:"default_setup_charge,omitempty"`

	DefaultRunCharge *DefaultRunCharge `xml:"defaultRunCharge,omitempty" json:"defaultRunCharge,omitempty" bson:"default_run_charge,omitempty"`

	ImprintSize *ImprintSize `xml:"imprintSize,omitempty" json:"imprintSize,omitempty" bson:"imprint_size,omitempty"`

	FobPointArray *FobPointArray `xml:"FobPointArray,omitempty" json:"FobPointArray,omitempty" bson:"fob_point_array,omitempty"`
}

type GetProductResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductResponse" bson:"-"`

	Product *Product `xml:"Product,omitempty" json:"Product,omitempty"`

	ServiceMessageArray *ServiceMessageArray `xml:"ServiceMessageArray,omitempty" json:"ServiceMessageArray,omitempty"`
}

type GetProductDateModifiedRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductDateModifiedRequest" bson:"-"`

	WsVersion *WsVersion `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *Id `xml:"id,omitempty" json:"id,omitempty"`

	Password *Password `xml:"password,omitempty" json:"password,omitempty"`

	ChangeTimeStamp *ChangeTimeStamp `xml:"changeTimeStamp,omitempty" json:"changeTimeStamp,omitempty"`
}

type ProductDateModified struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ ProductDateModified"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

	PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`
}

type GetProductDateModifiedResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductDateModifiedResponse" bson:"-"`

	ProductDateModifiedArray struct {
		ProductDateModified []*ProductDateModified `xml:"ProductDateModified,omitempty" json:"ProductDateModified,omitempty"`
	} `xml:"ProductDateModifiedArray,omitempty" json:"ProductDateModifiedArray,omitempty"`

	ServiceMessageArray *ServiceMessageArray `xml:"ServiceMessageArray,omitempty" json:"ServiceMessageArray,omitempty"`
}

type GetProductCloseOutRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductCloseOutRequest" bson:"-"`

	WsVersion *WsVersion `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *Id `xml:"id,omitempty" json:"id,omitempty"`

	Password *Password `xml:"password,omitempty" json:"password,omitempty"`
}

type ProductCloseOut struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ ProductCloseOut" bson:"-"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

	PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`
}

type GetProductCloseOutResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductCloseOutResponse" bson:"-"`

	ProductCloseOutArray struct {
		ProductCloseOut []*ProductCloseOut `xml:"ProductCloseOut,omitempty" json:"ProductCloseOut,omitempty"`
	} `xml:"ProductCloseOutArray,omitempty" json:"ProductCloseOutArray,omitempty"`

	ServiceMessageArray *ServiceMessageArray `xml:"ServiceMessageArray,omitempty" json:"ServiceMessageArray,omitempty"`
}

type GetProductSellableRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductSellableRequest" bson:"-"`

	WsVersion *WsVersion `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *Id `xml:"id,omitempty" json:"id,omitempty"`

	Password *Password `xml:"password,omitempty" json:"password,omitempty"`

	LocalizationCountry *LocalizationCountry `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *LocalizationLanguage `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`

	ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

	PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`

	LineName *LineName `xml:"lineName,omitempty" json:"lineName,omitempty"`

	IsSellable *IsSellable `xml:"isSellable,omitempty" json:"isSellable,omitempty"`
}

type GetProductSellableResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/ProductDataService/2.0.0/ GetProductSellableResponse" bson:"-"`

	ProductSellableArray struct {
		ProductSellable []struct {
			ProductId *ProductId `xml:"productId,omitempty" json:"productId,omitempty"`

			PartId *PartId `xml:"partId,omitempty" json:"partId,omitempty"`

			CulturePoint *CulturePoint `xml:"culturePoint,omitempty" json:"culturePoint,omitempty"`
		} `xml:"ProductSellable,omitempty" json:"ProductSellable,omitempty"`
	} `xml:"ProductSellableArray,omitempty" json:"ProductSellableArray,omitempty"`

	ServiceMessageArray *ServiceMessageArray `xml:"ServiceMessageArray,omitempty" json:"ServiceMessageArray,omitempty"`
}

type ProductDataService interface {
	GetProduct(request *GetProductRequest) (*GetProductResponse, error)

	GetProductContext(ctx context.Context, request *GetProductRequest) (*GetProductResponse, error)

	GetProductDateModified(request *GetProductDateModifiedRequest) (*GetProductDateModifiedResponse, error)

	GetProductDateModifiedContext(ctx context.Context, request *GetProductDateModifiedRequest) (*GetProductDateModifiedResponse, error)

	GetProductCloseOut(request *GetProductCloseOutRequest) (*GetProductCloseOutResponse, error)

	GetProductCloseOutContext(ctx context.Context, request *GetProductCloseOutRequest) (*GetProductCloseOutResponse, error)

	GetProductSellable(request *GetProductSellableRequest) (*GetProductSellableResponse, error)

	GetProductSellableContext(ctx context.Context, request *GetProductSellableRequest) (*GetProductSellableResponse, error)
}

type productDataService struct {
	client *soap.Client
}

func NewProductDataService(client *soap.Client) ProductDataService {
	return &productDataService{
		client: client,
	}
}

func (service *productDataService) GetProductContext(ctx context.Context, request *GetProductRequest) (*GetProductResponse, error) {
	response := new(GetProductResponse)
	err := service.client.CallContext(ctx, "getProduct", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *productDataService) GetProduct(request *GetProductRequest) (*GetProductResponse, error) {
	return service.GetProductContext(
		context.Background(),
		request,
	)
}

func (service *productDataService) GetProductDateModifiedContext(ctx context.Context, request *GetProductDateModifiedRequest) (*GetProductDateModifiedResponse, error) {
	response := new(GetProductDateModifiedResponse)
	err := service.client.CallContext(ctx, "getProductDateModified", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *productDataService) GetProductDateModified(request *GetProductDateModifiedRequest) (*GetProductDateModifiedResponse, error) {
	return service.GetProductDateModifiedContext(
		context.Background(),
		request,
	)
}

func (service *productDataService) GetProductCloseOutContext(ctx context.Context, request *GetProductCloseOutRequest) (*GetProductCloseOutResponse, error) {
	response := new(GetProductCloseOutResponse)
	err := service.client.CallContext(ctx, "getProductCloseOut", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *productDataService) GetProductCloseOut(request *GetProductCloseOutRequest) (*GetProductCloseOutResponse, error) {
	return service.GetProductCloseOutContext(
		context.Background(),
		request,
	)
}

func (service *productDataService) GetProductSellableContext(ctx context.Context, request *GetProductSellableRequest) (*GetProductSellableResponse, error) {
	response := new(GetProductSellableResponse)
	err := service.client.CallContext(ctx, "getProductSellable", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *productDataService) GetProductSellable(request *GetProductSellableRequest) (*GetProductSellableResponse, error) {
	return service.GetProductSellableContext(
		context.Background(),
		request,
	)
}
