// Code generated by gowsdl DO NOT EDIT.

package myservice

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"github.com/araddon/dateparse"
	"time"
)

type CustomTime struct {
	time.Time
}

func (c *CustomTime) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var v string
	d.DecodeElement(&v, &start)
	if v != "" {
		parse, err := dateparse.ParseAny(v)
		if err != nil {
			return err
		}
		*c = CustomTime{parse}
	}

	return nil
}

func (c *CustomTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	const shortForm = "2006-01-02T15:04:05"
	s := c.Format(shortForm)
	return e.EncodeElement(s, start)
}

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

//
// Two-letter (alpha-2) ISO 3166-1 code for one of the 243 countries.
//

type ISO3166CountyCode string

const (
	ISO3166CountyCodeAF ISO3166CountyCode = "AF"

	ISO3166CountyCodeAX ISO3166CountyCode = "AX"

	ISO3166CountyCodeAL ISO3166CountyCode = "AL"

	ISO3166CountyCodeDZ ISO3166CountyCode = "DZ"

	ISO3166CountyCodeAS ISO3166CountyCode = "AS"

	ISO3166CountyCodeAD ISO3166CountyCode = "AD"

	ISO3166CountyCodeAO ISO3166CountyCode = "AO"

	ISO3166CountyCodeAI ISO3166CountyCode = "AI"

	ISO3166CountyCodeAQ ISO3166CountyCode = "AQ"

	ISO3166CountyCodeAG ISO3166CountyCode = "AG"

	ISO3166CountyCodeAR ISO3166CountyCode = "AR"

	ISO3166CountyCodeAM ISO3166CountyCode = "AM"

	ISO3166CountyCodeAW ISO3166CountyCode = "AW"

	ISO3166CountyCodeAU ISO3166CountyCode = "AU"

	ISO3166CountyCodeAT ISO3166CountyCode = "AT"

	ISO3166CountyCodeAZ ISO3166CountyCode = "AZ"

	ISO3166CountyCodeBS ISO3166CountyCode = "BS"

	ISO3166CountyCodeBH ISO3166CountyCode = "BH"

	ISO3166CountyCodeBD ISO3166CountyCode = "BD"

	ISO3166CountyCodeBB ISO3166CountyCode = "BB"

	ISO3166CountyCodeBY ISO3166CountyCode = "BY"

	ISO3166CountyCodeBE ISO3166CountyCode = "BE"

	ISO3166CountyCodeBZ ISO3166CountyCode = "BZ"

	ISO3166CountyCodeBJ ISO3166CountyCode = "BJ"

	ISO3166CountyCodeBM ISO3166CountyCode = "BM"

	ISO3166CountyCodeBT ISO3166CountyCode = "BT"

	ISO3166CountyCodeBO ISO3166CountyCode = "BO"

	ISO3166CountyCodeBA ISO3166CountyCode = "BA"

	ISO3166CountyCodeBW ISO3166CountyCode = "BW"

	ISO3166CountyCodeBV ISO3166CountyCode = "BV"

	ISO3166CountyCodeBR ISO3166CountyCode = "BR"

	ISO3166CountyCodeIO ISO3166CountyCode = "IO"

	ISO3166CountyCodeBN ISO3166CountyCode = "BN"

	ISO3166CountyCodeBG ISO3166CountyCode = "BG"

	ISO3166CountyCodeBF ISO3166CountyCode = "BF"

	ISO3166CountyCodeBI ISO3166CountyCode = "BI"

	ISO3166CountyCodeKH ISO3166CountyCode = "KH"

	ISO3166CountyCodeCM ISO3166CountyCode = "CM"

	ISO3166CountyCodeCA ISO3166CountyCode = "CA"

	ISO3166CountyCodeCV ISO3166CountyCode = "CV"

	ISO3166CountyCodeKY ISO3166CountyCode = "KY"

	ISO3166CountyCodeCF ISO3166CountyCode = "CF"

	ISO3166CountyCodeTD ISO3166CountyCode = "TD"

	ISO3166CountyCodeCL ISO3166CountyCode = "CL"

	ISO3166CountyCodeCN ISO3166CountyCode = "CN"

	ISO3166CountyCodeCX ISO3166CountyCode = "CX"

	ISO3166CountyCodeCC ISO3166CountyCode = "CC"

	ISO3166CountyCodeCO ISO3166CountyCode = "CO"

	ISO3166CountyCodeKM ISO3166CountyCode = "KM"

	ISO3166CountyCodeCG ISO3166CountyCode = "CG"

	ISO3166CountyCodeCD ISO3166CountyCode = "CD"

	ISO3166CountyCodeCK ISO3166CountyCode = "CK"

	ISO3166CountyCodeCR ISO3166CountyCode = "CR"

	ISO3166CountyCodeCI ISO3166CountyCode = "CI"

	ISO3166CountyCodeHR ISO3166CountyCode = "HR"

	ISO3166CountyCodeCU ISO3166CountyCode = "CU"

	ISO3166CountyCodeCY ISO3166CountyCode = "CY"

	ISO3166CountyCodeCZ ISO3166CountyCode = "CZ"

	ISO3166CountyCodeDK ISO3166CountyCode = "DK"

	ISO3166CountyCodeDJ ISO3166CountyCode = "DJ"

	ISO3166CountyCodeDM ISO3166CountyCode = "DM"

	ISO3166CountyCodeDO ISO3166CountyCode = "DO"

	ISO3166CountyCodeEC ISO3166CountyCode = "EC"

	ISO3166CountyCodeEG ISO3166CountyCode = "EG"

	ISO3166CountyCodeSV ISO3166CountyCode = "SV"

	ISO3166CountyCodeGQ ISO3166CountyCode = "GQ"

	ISO3166CountyCodeER ISO3166CountyCode = "ER"

	ISO3166CountyCodeEE ISO3166CountyCode = "EE"

	ISO3166CountyCodeET ISO3166CountyCode = "ET"

	ISO3166CountyCodeFK ISO3166CountyCode = "FK"

	ISO3166CountyCodeFO ISO3166CountyCode = "FO"

	ISO3166CountyCodeFJ ISO3166CountyCode = "FJ"

	ISO3166CountyCodeFI ISO3166CountyCode = "FI"

	ISO3166CountyCodeFR ISO3166CountyCode = "FR"

	ISO3166CountyCodeGF ISO3166CountyCode = "GF"

	ISO3166CountyCodePF ISO3166CountyCode = "PF"

	ISO3166CountyCodeTF ISO3166CountyCode = "TF"

	ISO3166CountyCodeGA ISO3166CountyCode = "GA"

	ISO3166CountyCodeGM ISO3166CountyCode = "GM"

	ISO3166CountyCodeGE ISO3166CountyCode = "GE"

	ISO3166CountyCodeDE ISO3166CountyCode = "DE"

	ISO3166CountyCodeGH ISO3166CountyCode = "GH"

	ISO3166CountyCodeGI ISO3166CountyCode = "GI"

	ISO3166CountyCodeGR ISO3166CountyCode = "GR"

	ISO3166CountyCodeGL ISO3166CountyCode = "GL"

	ISO3166CountyCodeGD ISO3166CountyCode = "GD"

	ISO3166CountyCodeGP ISO3166CountyCode = "GP"

	ISO3166CountyCodeGU ISO3166CountyCode = "GU"

	ISO3166CountyCodeGT ISO3166CountyCode = "GT"

	ISO3166CountyCodeGG ISO3166CountyCode = "GG"

	ISO3166CountyCodeGN ISO3166CountyCode = "GN"

	ISO3166CountyCodeGW ISO3166CountyCode = "GW"

	ISO3166CountyCodeGY ISO3166CountyCode = "GY"

	ISO3166CountyCodeHT ISO3166CountyCode = "HT"

	ISO3166CountyCodeHM ISO3166CountyCode = "HM"

	ISO3166CountyCodeVA ISO3166CountyCode = "VA"

	ISO3166CountyCodeHN ISO3166CountyCode = "HN"

	ISO3166CountyCodeHK ISO3166CountyCode = "HK"

	ISO3166CountyCodeHU ISO3166CountyCode = "HU"

	ISO3166CountyCodeIS ISO3166CountyCode = "IS"

	ISO3166CountyCodeIN ISO3166CountyCode = "IN"

	ISO3166CountyCodeID ISO3166CountyCode = "ID"

	ISO3166CountyCodeIR ISO3166CountyCode = "IR"

	ISO3166CountyCodeIQ ISO3166CountyCode = "IQ"

	ISO3166CountyCodeIE ISO3166CountyCode = "IE"

	ISO3166CountyCodeIM ISO3166CountyCode = "IM"

	ISO3166CountyCodeIL ISO3166CountyCode = "IL"

	ISO3166CountyCodeIT ISO3166CountyCode = "IT"

	ISO3166CountyCodeJM ISO3166CountyCode = "JM"

	ISO3166CountyCodeJP ISO3166CountyCode = "JP"

	ISO3166CountyCodeJE ISO3166CountyCode = "JE"

	ISO3166CountyCodeJO ISO3166CountyCode = "JO"

	ISO3166CountyCodeKZ ISO3166CountyCode = "KZ"

	ISO3166CountyCodeKE ISO3166CountyCode = "KE"

	ISO3166CountyCodeKI ISO3166CountyCode = "KI"

	ISO3166CountyCodeKP ISO3166CountyCode = "KP"

	ISO3166CountyCodeKR ISO3166CountyCode = "KR"

	ISO3166CountyCodeKW ISO3166CountyCode = "KW"

	ISO3166CountyCodeKG ISO3166CountyCode = "KG"

	ISO3166CountyCodeLA ISO3166CountyCode = "LA"

	ISO3166CountyCodeLV ISO3166CountyCode = "LV"

	ISO3166CountyCodeLB ISO3166CountyCode = "LB"

	ISO3166CountyCodeLS ISO3166CountyCode = "LS"

	ISO3166CountyCodeLR ISO3166CountyCode = "LR"

	ISO3166CountyCodeLY ISO3166CountyCode = "LY"

	ISO3166CountyCodeLI ISO3166CountyCode = "LI"

	ISO3166CountyCodeLT ISO3166CountyCode = "LT"

	ISO3166CountyCodeLU ISO3166CountyCode = "LU"

	ISO3166CountyCodeMO ISO3166CountyCode = "MO"

	ISO3166CountyCodeMK ISO3166CountyCode = "MK"

	ISO3166CountyCodeMG ISO3166CountyCode = "MG"

	ISO3166CountyCodeMW ISO3166CountyCode = "MW"

	ISO3166CountyCodeMY ISO3166CountyCode = "MY"

	ISO3166CountyCodeMV ISO3166CountyCode = "MV"

	ISO3166CountyCodeML ISO3166CountyCode = "ML"

	ISO3166CountyCodeMT ISO3166CountyCode = "MT"

	ISO3166CountyCodeMH ISO3166CountyCode = "MH"

	ISO3166CountyCodeMQ ISO3166CountyCode = "MQ"

	ISO3166CountyCodeMR ISO3166CountyCode = "MR"

	ISO3166CountyCodeMU ISO3166CountyCode = "MU"

	ISO3166CountyCodeYT ISO3166CountyCode = "YT"

	ISO3166CountyCodeMX ISO3166CountyCode = "MX"

	ISO3166CountyCodeFM ISO3166CountyCode = "FM"

	ISO3166CountyCodeMD ISO3166CountyCode = "MD"

	ISO3166CountyCodeMC ISO3166CountyCode = "MC"

	ISO3166CountyCodeMN ISO3166CountyCode = "MN"

	ISO3166CountyCodeMS ISO3166CountyCode = "MS"

	ISO3166CountyCodeMA ISO3166CountyCode = "MA"

	ISO3166CountyCodeMZ ISO3166CountyCode = "MZ"

	ISO3166CountyCodeMM ISO3166CountyCode = "MM"

	ISO3166CountyCodeNA ISO3166CountyCode = "NA"

	ISO3166CountyCodeNR ISO3166CountyCode = "NR"

	ISO3166CountyCodeNP ISO3166CountyCode = "NP"

	ISO3166CountyCodeNL ISO3166CountyCode = "NL"

	ISO3166CountyCodeAN ISO3166CountyCode = "AN"

	ISO3166CountyCodeNC ISO3166CountyCode = "NC"

	ISO3166CountyCodeNZ ISO3166CountyCode = "NZ"

	ISO3166CountyCodeNI ISO3166CountyCode = "NI"

	ISO3166CountyCodeNE ISO3166CountyCode = "NE"

	ISO3166CountyCodeNG ISO3166CountyCode = "NG"

	ISO3166CountyCodeNU ISO3166CountyCode = "NU"

	ISO3166CountyCodeNF ISO3166CountyCode = "NF"

	ISO3166CountyCodeMP ISO3166CountyCode = "MP"

	ISO3166CountyCodeNO ISO3166CountyCode = "NO"

	ISO3166CountyCodeOM ISO3166CountyCode = "OM"

	ISO3166CountyCodePK ISO3166CountyCode = "PK"

	ISO3166CountyCodePW ISO3166CountyCode = "PW"

	ISO3166CountyCodePS ISO3166CountyCode = "PS"

	ISO3166CountyCodePA ISO3166CountyCode = "PA"

	ISO3166CountyCodePG ISO3166CountyCode = "PG"

	ISO3166CountyCodePY ISO3166CountyCode = "PY"

	ISO3166CountyCodePE ISO3166CountyCode = "PE"

	ISO3166CountyCodePH ISO3166CountyCode = "PH"

	ISO3166CountyCodePN ISO3166CountyCode = "PN"

	ISO3166CountyCodePL ISO3166CountyCode = "PL"

	ISO3166CountyCodePT ISO3166CountyCode = "PT"

	ISO3166CountyCodePR ISO3166CountyCode = "PR"

	ISO3166CountyCodeQA ISO3166CountyCode = "QA"

	ISO3166CountyCodeRE ISO3166CountyCode = "RE"

	ISO3166CountyCodeRO ISO3166CountyCode = "RO"

	ISO3166CountyCodeRU ISO3166CountyCode = "RU"

	ISO3166CountyCodeRW ISO3166CountyCode = "RW"

	ISO3166CountyCodeSH ISO3166CountyCode = "SH"

	ISO3166CountyCodeKN ISO3166CountyCode = "KN"

	ISO3166CountyCodeLC ISO3166CountyCode = "LC"

	ISO3166CountyCodePM ISO3166CountyCode = "PM"

	ISO3166CountyCodeVC ISO3166CountyCode = "VC"

	ISO3166CountyCodeWS ISO3166CountyCode = "WS"

	ISO3166CountyCodeSM ISO3166CountyCode = "SM"

	ISO3166CountyCodeST ISO3166CountyCode = "ST"

	ISO3166CountyCodeSA ISO3166CountyCode = "SA"

	ISO3166CountyCodeSN ISO3166CountyCode = "SN"

	ISO3166CountyCodeCS ISO3166CountyCode = "CS"

	ISO3166CountyCodeSC ISO3166CountyCode = "SC"

	ISO3166CountyCodeSL ISO3166CountyCode = "SL"

	ISO3166CountyCodeSG ISO3166CountyCode = "SG"

	ISO3166CountyCodeSK ISO3166CountyCode = "SK"

	ISO3166CountyCodeSI ISO3166CountyCode = "SI"

	ISO3166CountyCodeSB ISO3166CountyCode = "SB"

	ISO3166CountyCodeSO ISO3166CountyCode = "SO"

	ISO3166CountyCodeZA ISO3166CountyCode = "ZA"

	ISO3166CountyCodeGS ISO3166CountyCode = "GS"

	ISO3166CountyCodeES ISO3166CountyCode = "ES"

	ISO3166CountyCodeLK ISO3166CountyCode = "LK"

	ISO3166CountyCodeSD ISO3166CountyCode = "SD"

	ISO3166CountyCodeSR ISO3166CountyCode = "SR"

	ISO3166CountyCodeSJ ISO3166CountyCode = "SJ"

	ISO3166CountyCodeSZ ISO3166CountyCode = "SZ"

	ISO3166CountyCodeSE ISO3166CountyCode = "SE"

	ISO3166CountyCodeCH ISO3166CountyCode = "CH"

	ISO3166CountyCodeSY ISO3166CountyCode = "SY"

	ISO3166CountyCodeTW ISO3166CountyCode = "TW"

	ISO3166CountyCodeTJ ISO3166CountyCode = "TJ"

	ISO3166CountyCodeTZ ISO3166CountyCode = "TZ"

	ISO3166CountyCodeTH ISO3166CountyCode = "TH"

	ISO3166CountyCodeTL ISO3166CountyCode = "TL"

	ISO3166CountyCodeTG ISO3166CountyCode = "TG"

	ISO3166CountyCodeTK ISO3166CountyCode = "TK"

	ISO3166CountyCodeTO ISO3166CountyCode = "TO"

	ISO3166CountyCodeTT ISO3166CountyCode = "TT"

	ISO3166CountyCodeTN ISO3166CountyCode = "TN"

	ISO3166CountyCodeTR ISO3166CountyCode = "TR"

	ISO3166CountyCodeTM ISO3166CountyCode = "TM"

	ISO3166CountyCodeTC ISO3166CountyCode = "TC"

	ISO3166CountyCodeTV ISO3166CountyCode = "TV"

	ISO3166CountyCodeUG ISO3166CountyCode = "UG"

	ISO3166CountyCodeUA ISO3166CountyCode = "UA"

	ISO3166CountyCodeAE ISO3166CountyCode = "AE"

	ISO3166CountyCodeGB ISO3166CountyCode = "GB"

	ISO3166CountyCodeUS ISO3166CountyCode = "US"

	ISO3166CountyCodeUM ISO3166CountyCode = "UM"

	ISO3166CountyCodeUY ISO3166CountyCode = "UY"

	ISO3166CountyCodeUZ ISO3166CountyCode = "UZ"

	ISO3166CountyCodeVU ISO3166CountyCode = "VU"

	ISO3166CountyCodeVE ISO3166CountyCode = "VE"

	ISO3166CountyCodeVN ISO3166CountyCode = "VN"

	ISO3166CountyCodeVG ISO3166CountyCode = "VG"

	ISO3166CountyCodeVI ISO3166CountyCode = "VI"

	ISO3166CountyCodeWF ISO3166CountyCode = "WF"

	ISO3166CountyCodeEH ISO3166CountyCode = "EH"

	ISO3166CountyCodeYE ISO3166CountyCode = "YE"

	ISO3166CountyCodeZM ISO3166CountyCode = "ZM"

	ISO3166CountyCodeZW ISO3166CountyCode = "ZW"
)

type CurrencyNameType string

const (
	CurrencyNameTypeAfghanistanAfghani CurrencyNameType = "Afghanistan Afghani"

	CurrencyNameTypeAlbaniaLek CurrencyNameType = "Albania Lek"

	CurrencyNameTypeAlgerianDinar CurrencyNameType = "Algerian Dinar"

	CurrencyNameTypeAngolaNewKwanza CurrencyNameType = "Angola New Kwanza"

	CurrencyNameTypeArgentinePeso CurrencyNameType = "Argentine Peso"

	CurrencyNameTypeArmenianDram CurrencyNameType = "Armenian Dram"

	CurrencyNameTypeArubanGuilder CurrencyNameType = "Aruban Guilder"

	CurrencyNameTypeAustralianDollar CurrencyNameType = "Australian Dollar"

	CurrencyNameTypeAustrianSchilling CurrencyNameType = "Austrian Schilling"

	CurrencyNameTypeAzerbaijanianManat CurrencyNameType = "Azerbaijanian Manat"

	CurrencyNameTypeBahamianDollar CurrencyNameType = "Bahamian Dollar"

	CurrencyNameTypeBahrainiDinar CurrencyNameType = "Bahraini Dinar"

	CurrencyNameTypeBangladeshTaka CurrencyNameType = "BangladeshTaka"

	CurrencyNameTypeBarbadosDollar CurrencyNameType = "Barbados Dollar"

	CurrencyNameTypeBelarussianRuble CurrencyNameType = "Belarussian Ruble"

	CurrencyNameTypeBelgianFranc CurrencyNameType = "Belgian Franc"

	CurrencyNameTypeBelizeDollar CurrencyNameType = "Belize Dollar"

	CurrencyNameTypeBermudianDollar CurrencyNameType = "Bermudian Dollar"

	CurrencyNameTypeBhutanNgultrum CurrencyNameType = "Bhutan Ngultrum"

	CurrencyNameTypeBoliviaBoliviano CurrencyNameType = "Bolivia Boliviano"

	CurrencyNameTypeBosniaConvertibleMark CurrencyNameType = "Bosnia Convertible Mark"

	CurrencyNameTypeBotswanaPula CurrencyNameType = "Botswana Pula"

	CurrencyNameTypeBrazilianReal CurrencyNameType = "Brazilian Real"

	CurrencyNameTypeBruneiDollar CurrencyNameType = "Brunei Dollar"

	CurrencyNameTypeBulgariaLev CurrencyNameType = "Bulgaria Lev"

	CurrencyNameTypeBurundiFranc CurrencyNameType = "Burundi Franc"

	CurrencyNameTypeCambodiaRiel CurrencyNameType = "Cambodia Riel"

	CurrencyNameTypeCanadianDollar CurrencyNameType = "Canadian Dollar"

	CurrencyNameTypeCapeVerdeEscudo CurrencyNameType = "Cape Verde Escudo"

	CurrencyNameTypeCaymanIslandsDollar CurrencyNameType = "Cayman Islands Dollar"

	CurrencyNameTypeCFAFrancBCEAO CurrencyNameType = "CFA Franc BCEAO"

	CurrencyNameTypeCFAFrancBEAC CurrencyNameType = "CFA Franc BEAC"

	CurrencyNameTypeCFPFranc CurrencyNameType = "CFP Franc"

	CurrencyNameTypeChileanPeso CurrencyNameType = "Chilean Peso"

	CurrencyNameTypeChineseYuanRenminbi CurrencyNameType = "Chinese Yuan Renminbi"

	CurrencyNameTypeColumbianPeso CurrencyNameType = "Columbian Peso"

	CurrencyNameTypeComoroFranc CurrencyNameType = "Comoro Franc"

	CurrencyNameTypeCongoFranc CurrencyNameType = "Congo Franc"

	CurrencyNameTypeCostaRicanColon CurrencyNameType = "Costa Rican Colon"

	CurrencyNameTypeCroatianKuna CurrencyNameType = "Croatian Kuna"

	CurrencyNameTypeCubanPeso CurrencyNameType = "Cuban Peso"

	CurrencyNameTypeCyprusPound CurrencyNameType = "Cyprus Pound"

	CurrencyNameTypeCzechKoruna CurrencyNameType = "Czech Koruna"

	CurrencyNameTypeDanishKrone CurrencyNameType = "Danish Krone"

	CurrencyNameTypeDeutscheMark CurrencyNameType = "Deutsche Mark"

	CurrencyNameTypeDijiboutiFranc CurrencyNameType = "Dijibouti Franc"

	CurrencyNameTypeDominicanPeso CurrencyNameType = "Dominican Peso"

	CurrencyNameTypeDutchGuilder CurrencyNameType = "Dutch Guilder"

	CurrencyNameTypeEastCaribbeanDollar CurrencyNameType = "East Caribbean Dollar"

	CurrencyNameTypeEcuadorSucre CurrencyNameType = "Ecuador Sucre"

	CurrencyNameTypeEgyptianPound CurrencyNameType = "Egyptian  Pound"

	CurrencyNameTypeElSalvadorianColon CurrencyNameType = "El Salvadorian Colon"

	CurrencyNameTypeEritreaNakfa CurrencyNameType = "Eritrea Nakfa"

	CurrencyNameTypeEscudoCaboverdiano CurrencyNameType = "Escudo Caboverdiano"

	CurrencyNameTypeEstoniaKroon CurrencyNameType = "Estonia Kroon"

	CurrencyNameTypeEthiopiaBirr CurrencyNameType = "Ethiopia Birr"

	CurrencyNameTypeEuro CurrencyNameType = "Euro"

	CurrencyNameTypeFalklandPound CurrencyNameType = "Falkland Pound"

	CurrencyNameTypeFijiDollar CurrencyNameType = "Fiji Dollar"

	CurrencyNameTypeFinnishMarkka CurrencyNameType = "Finnish Markka"

	CurrencyNameTypeFrenchFranc CurrencyNameType = "French Franc"

	CurrencyNameTypeGambiaDalasi CurrencyNameType = "Gambia Dalasi"

	CurrencyNameTypeGeorgiaLari CurrencyNameType = "Georgia Lari"

	CurrencyNameTypeGhanaCedi CurrencyNameType = "Ghana Cedi"

	CurrencyNameTypeGibraltarPound CurrencyNameType = "Gibraltar Pound"

	CurrencyNameTypeGreekDrachma CurrencyNameType = "Greek Drachma"

	CurrencyNameTypeGuatemalaQuetzal CurrencyNameType = "Guatemala Quetzal"

	CurrencyNameTypeGuyanaDollar CurrencyNameType = "Guyana Dollar"

	CurrencyNameTypeHaitiGourde CurrencyNameType = "Haiti Gourde"

	CurrencyNameTypeHondurasLempira CurrencyNameType = "Honduras Lempira"

	CurrencyNameTypeHongKongDollar CurrencyNameType = "Hong Kong Dollar"

	CurrencyNameTypeHungaryForint CurrencyNameType = "Hungary Forint"

	CurrencyNameTypeIcelandicKrona CurrencyNameType = "Icelandic Krona"

	CurrencyNameTypeIndianRupee CurrencyNameType = "Indian Rupee"

	CurrencyNameTypeIndonesiaRupiah CurrencyNameType = "Indonesia Rupiah"

	CurrencyNameTypeIranianRiyal CurrencyNameType = "Iranian Riyal"

	CurrencyNameTypeIraqiDinar CurrencyNameType = "Iraqi Dinar"

	CurrencyNameTypeIrishPunt CurrencyNameType = "Irish Punt"

	CurrencyNameTypeIsraelShekel CurrencyNameType = "Israel Shekel"

	CurrencyNameTypeItalianLira CurrencyNameType = "Italian Lira"

	CurrencyNameTypeJamaicanDollar CurrencyNameType = "Jamaican Dollar"

	CurrencyNameTypeJapaneseYen CurrencyNameType = "Japanese Yen"

	CurrencyNameTypeJordanianDinar CurrencyNameType = "Jordanian Dinar"

	CurrencyNameTypeKazakhstanTenge CurrencyNameType = "Kazakhstan Tenge"

	CurrencyNameTypeKenyanShilling CurrencyNameType = "Kenyan Shilling"

	CurrencyNameTypeKuwaitiDinar CurrencyNameType = "Kuwaiti Dinar"

	CurrencyNameTypeKyrgyzstanSom CurrencyNameType = "Kyrgyzstan Som"

	CurrencyNameTypeLaosKip CurrencyNameType = "Laos Kip"

	CurrencyNameTypeLatviaLat CurrencyNameType = "Latvia Lat"

	CurrencyNameTypeLebanesePound CurrencyNameType = "Lebanese Pound"

	CurrencyNameTypeLesothoMaloti CurrencyNameType = "Lesotho Maloti"

	CurrencyNameTypeLiberianDollar CurrencyNameType = "Liberian Dollar"

	CurrencyNameTypeLibyanDinar CurrencyNameType = "Libyan Dinar"

	CurrencyNameTypeLithuaniaLitas CurrencyNameType = "Lithuania Litas"

	CurrencyNameTypeLuxembourgFranc CurrencyNameType = "Luxembourg Franc"

	CurrencyNameTypeMacaoPataca CurrencyNameType = "Macao Pataca"

	CurrencyNameTypeMacedonianDenar CurrencyNameType = "Macedonian Denar"

	CurrencyNameTypeMalagasyFranc CurrencyNameType = "Malagasy Franc"

	CurrencyNameTypeMalawianKwacha CurrencyNameType = "Malawian Kwacha"

	CurrencyNameTypeMalaysianRinggit CurrencyNameType = "Malaysian Ringgit"

	CurrencyNameTypeMaldivesRufiyaa CurrencyNameType = "Maldives Rufiyaa"

	CurrencyNameTypeMalteseLira CurrencyNameType = "Maltese Lira"

	CurrencyNameTypeMauritaniaOuguiya CurrencyNameType = "Mauritania Ouguiya"

	CurrencyNameTypeMauritiusRupee CurrencyNameType = "Mauritius Rupee"

	CurrencyNameTypeMexicanPeso CurrencyNameType = "Mexican Peso"

	CurrencyNameTypeMoldovianLeu CurrencyNameType = "Moldovian Leu"

	CurrencyNameTypeMongoliaTugrik CurrencyNameType = "Mongolia Tugrik"

	CurrencyNameTypeMoroccanDirham CurrencyNameType = "Moroccan Dirham"

	CurrencyNameTypeMozambiqueMetical CurrencyNameType = "Mozambique Metical"

	CurrencyNameTypeMyanmarKyat CurrencyNameType = "Myanmar Kyat"

	CurrencyNameTypeNamibianDollar CurrencyNameType = "Namibian Dollar"

	CurrencyNameTypeNepaleseRupee CurrencyNameType = "Nepalese Rupee"

	CurrencyNameTypeNetherlandsAntillesGuilder CurrencyNameType = "Netherlands Antilles Guilder"

	CurrencyNameTypeNewZaire CurrencyNameType = "New Zaire"

	CurrencyNameTypeNewZealandDollar CurrencyNameType = "New Zealand Dollar"

	CurrencyNameTypeNicaraguaCordoba CurrencyNameType = "Nicaragua Cordoba"

	CurrencyNameTypeNigeriaNaira CurrencyNameType = "Nigeria Naira"

	CurrencyNameTypeNorthKoreanWon CurrencyNameType = "North Korean Won"

	CurrencyNameTypeNorwegianKrone CurrencyNameType = "Norwegian Krone"

	CurrencyNameTypePakistaniRupee CurrencyNameType = "Pakistani Rupee"

	CurrencyNameTypePanamaBalboa CurrencyNameType = "Panama Balboa"

	CurrencyNameTypePapuaNewGuineaKina CurrencyNameType = "Papua New Guinea Kina"

	CurrencyNameTypeParaguayGuarani CurrencyNameType = "Paraguay Guarani"

	CurrencyNameTypePeruNewSol CurrencyNameType = "Peru New Sol"

	CurrencyNameTypePhilippinePeso CurrencyNameType = "Philippine Peso"

	CurrencyNameTypePolandNewZloty CurrencyNameType = "Poland New Zloty"

	CurrencyNameTypePortugueseEscudo CurrencyNameType = "Portuguese Escudo"

	CurrencyNameTypeQatariRiyal CurrencyNameType = "Qatari Riyal"

	CurrencyNameTypeRiyalOmani CurrencyNameType = "Riyal Omani"

	CurrencyNameTypeRomanianLeu CurrencyNameType = "Romanian Leu"

	CurrencyNameTypeRussianFederationRouble CurrencyNameType = "Russian Federation Rouble"

	CurrencyNameTypeRwandaFranc CurrencyNameType = "Rwanda Franc"

	CurrencyNameTypeSaoTomeandPrincipeDobra CurrencyNameType = "Sao Tome and Principe Dobra"

	CurrencyNameTypeSaudiRiyal CurrencyNameType = "Saudi Riyal"

	CurrencyNameTypeSeychellesRupee CurrencyNameType = "Seychelles Rupee"

	CurrencyNameTypeSierraLeoneLeone CurrencyNameType = "Sierra Leone Leone"

	CurrencyNameTypeSingaporeDollar CurrencyNameType = "Singapore Dollar"

	CurrencyNameTypeSlovakDoruna CurrencyNameType = "Slovak Doruna"

	CurrencyNameTypeSloveniaTolar CurrencyNameType = "Slovenia Tolar"

	CurrencyNameTypeSolomanIslandsDollar CurrencyNameType = "Soloman Islands Dollar"

	CurrencyNameTypeSomaliaShilling CurrencyNameType = "Somalia Shilling"

	CurrencyNameTypeSouthAfricanRand CurrencyNameType = "South African Rand"

	CurrencyNameTypeSouthKoereanWon CurrencyNameType = "South Koerean Won"

	CurrencyNameTypeSpanishPeseta CurrencyNameType = "Spanish Peseta"

	CurrencyNameTypeSriLankanRupee CurrencyNameType = "Sri Lankan Rupee"

	CurrencyNameTypeStHelenaPound CurrencyNameType = "St Helena Pound"

	CurrencyNameTypeSterling CurrencyNameType = "Sterling"

	CurrencyNameTypeSudanesePound CurrencyNameType = "Sudanese Pound"

	CurrencyNameTypeSurinamGuilder CurrencyNameType = "Surinam Guilder"

	CurrencyNameTypeSwazilandLilangeni CurrencyNameType = "Swaziland Lilangeni"

	CurrencyNameTypeSwedishKrona CurrencyNameType = "Swedish Krona"

	CurrencyNameTypeSwissFranc CurrencyNameType = "Swiss Franc"

	CurrencyNameTypeSyrianPound CurrencyNameType = "Syrian Pound"

	CurrencyNameTypeTaiwaneseNTDollar CurrencyNameType = "Taiwanese NT Dollar"

	CurrencyNameTypeTajikistanRuble CurrencyNameType = "Tajikistan Ruble"

	CurrencyNameTypeTanzanianShilling CurrencyNameType = "Tanzanian Shilling"

	CurrencyNameTypeThailandBaht CurrencyNameType = "Thailand Baht"

	CurrencyNameTypeTimorEscudo CurrencyNameType = "Timor Escudo"

	CurrencyNameTypeTongaPalanga CurrencyNameType = "Tonga Palanga"

	CurrencyNameTypeTrinidadandTobagoDollar CurrencyNameType = "Trinidad and Tobago Dollar"

	CurrencyNameTypeTunasiaTunisianDinar CurrencyNameType = "Tunasia Tunisian Dinar"

	CurrencyNameTypeTurkishLira CurrencyNameType = "Turkish Lira"

	CurrencyNameTypeTurkmenistanManat CurrencyNameType = "Turkmenistan Manat"

	CurrencyNameTypeUAEDirham CurrencyNameType = "UAE Dirham"

	CurrencyNameTypeUgandianShilling CurrencyNameType = "Ugandian Shilling"

	CurrencyNameTypeUkraineHryvna CurrencyNameType = "Ukraine Hryvna"

	CurrencyNameTypeUruguayanNewPeso CurrencyNameType = "Uruguayan New Peso"

	CurrencyNameTypeUnitedStatesofAmericaDollar CurrencyNameType = "United States of America Dollar"

	CurrencyNameTypeUzbekistaniSum CurrencyNameType = "Uzbekistani Sum"

	CurrencyNameTypeVanuatuVatu CurrencyNameType = "Vanuatu Vatu"

	CurrencyNameTypeVenezuelaBolivar CurrencyNameType = "Venezuela Bolivar"

	CurrencyNameTypeVietnamDong CurrencyNameType = "Vietnam Dong"

	CurrencyNameTypeWesternSomoaTala CurrencyNameType = "Western Somoa Tala"

	CurrencyNameTypeYemenRiyal CurrencyNameType = "Yemen Riyal"

	CurrencyNameTypeYugoslaviaNewDinar CurrencyNameType = "Yugoslavia New Dinar"

	CurrencyNameTypeZambianKwacha CurrencyNameType = "Zambian Kwacha"

	CurrencyNameTypeZimbabweDollar CurrencyNameType = "Zimbabwe Dollar"
)

type CurrencyCodeType string

const (
	CurrencyCodeTypeAFA CurrencyCodeType = "AFA"

	CurrencyCodeTypeALL CurrencyCodeType = "ALL"

	CurrencyCodeTypeDZD CurrencyCodeType = "DZD"

	CurrencyCodeTypeAON CurrencyCodeType = "AON"

	CurrencyCodeTypeARS CurrencyCodeType = "ARS"

	CurrencyCodeTypeAMD CurrencyCodeType = "AMD"

	CurrencyCodeTypeAWG CurrencyCodeType = "AWG"

	CurrencyCodeTypeAUD CurrencyCodeType = "AUD"

	CurrencyCodeTypeATS CurrencyCodeType = "ATS"

	CurrencyCodeTypeAZM CurrencyCodeType = "AZM"

	CurrencyCodeTypeBSD CurrencyCodeType = "BSD"

	CurrencyCodeTypeBHD CurrencyCodeType = "BHD"

	CurrencyCodeTypeBDT CurrencyCodeType = "BDT"

	CurrencyCodeTypeBBD CurrencyCodeType = "BBD"

	CurrencyCodeTypeBYR CurrencyCodeType = "BYR"

	CurrencyCodeTypeBEF CurrencyCodeType = "BEF"

	CurrencyCodeTypeBZD CurrencyCodeType = "BZD"

	CurrencyCodeTypeBMD CurrencyCodeType = "BMD"

	CurrencyCodeTypeBTN CurrencyCodeType = "BTN"

	CurrencyCodeTypeBOB CurrencyCodeType = "BOB"

	CurrencyCodeTypeBAM CurrencyCodeType = "BAM"

	CurrencyCodeTypeBWP CurrencyCodeType = "BWP"

	CurrencyCodeTypeBRL CurrencyCodeType = "BRL"

	CurrencyCodeTypeBND CurrencyCodeType = "BND"

	CurrencyCodeTypeBGL CurrencyCodeType = "BGL"

	CurrencyCodeTypeBIF CurrencyCodeType = "BIF"

	CurrencyCodeTypeKHR CurrencyCodeType = "KHR"

	CurrencyCodeTypeCAD CurrencyCodeType = "CAD"

	CurrencyCodeTypeCVE CurrencyCodeType = "CVE"

	CurrencyCodeTypeKYD CurrencyCodeType = "KYD"

	CurrencyCodeTypeXOF CurrencyCodeType = "XOF"

	CurrencyCodeTypeXAF CurrencyCodeType = "XAF"

	CurrencyCodeTypeXPF CurrencyCodeType = "XPF"

	CurrencyCodeTypeCLP CurrencyCodeType = "CLP"

	CurrencyCodeTypeCNY CurrencyCodeType = "CNY"

	CurrencyCodeTypeCOP CurrencyCodeType = "COP"

	CurrencyCodeTypeKMF CurrencyCodeType = "KMF"

	CurrencyCodeTypeCDF CurrencyCodeType = "CDF"

	CurrencyCodeTypeCRC CurrencyCodeType = "CRC"

	CurrencyCodeTypeHRK CurrencyCodeType = "HRK"

	CurrencyCodeTypeCUP CurrencyCodeType = "CUP"

	CurrencyCodeTypeCYP CurrencyCodeType = "CYP"

	CurrencyCodeTypeCZK CurrencyCodeType = "CZK"

	CurrencyCodeTypeDKK CurrencyCodeType = "DKK"

	CurrencyCodeTypeDEM CurrencyCodeType = "DEM"

	CurrencyCodeTypeDJF CurrencyCodeType = "DJF"

	CurrencyCodeTypeDOP CurrencyCodeType = "DOP"

	CurrencyCodeTypeNLG CurrencyCodeType = "NLG"

	CurrencyCodeTypeXCD CurrencyCodeType = "XCD"

	CurrencyCodeTypeECS CurrencyCodeType = "ECS"

	CurrencyCodeTypeEGP CurrencyCodeType = "EGP"

	CurrencyCodeTypeSVC CurrencyCodeType = "SVC"

	CurrencyCodeTypeERN CurrencyCodeType = "ERN"

	CurrencyCodeTypeEEK CurrencyCodeType = "EEK"

	CurrencyCodeTypeETB CurrencyCodeType = "ETB"

	CurrencyCodeTypeEUR CurrencyCodeType = "EUR"

	CurrencyCodeTypeFKP CurrencyCodeType = "FKP"

	CurrencyCodeTypeFJD CurrencyCodeType = "FJD"

	CurrencyCodeTypeFIM CurrencyCodeType = "FIM"

	CurrencyCodeTypeFRF CurrencyCodeType = "FRF"

	CurrencyCodeTypeGMD CurrencyCodeType = "GMD"

	CurrencyCodeTypeGEL CurrencyCodeType = "GEL"

	CurrencyCodeTypeGHC CurrencyCodeType = "GHC"

	CurrencyCodeTypeGIP CurrencyCodeType = "GIP"

	CurrencyCodeTypeGRD CurrencyCodeType = "GRD"

	CurrencyCodeTypeGTQ CurrencyCodeType = "GTQ"

	CurrencyCodeTypeGYD CurrencyCodeType = "GYD"

	CurrencyCodeTypeHTG CurrencyCodeType = "HTG"

	CurrencyCodeTypeHNL CurrencyCodeType = "HNL"

	CurrencyCodeTypeHKD CurrencyCodeType = "HKD"

	CurrencyCodeTypeHUF CurrencyCodeType = "HUF"

	CurrencyCodeTypeISK CurrencyCodeType = "ISK"

	CurrencyCodeTypeINR CurrencyCodeType = "INR"

	CurrencyCodeTypeIDR CurrencyCodeType = "IDR"

	CurrencyCodeTypeIRR CurrencyCodeType = "IRR"

	CurrencyCodeTypeIQD CurrencyCodeType = "IQD"

	CurrencyCodeTypeIEP CurrencyCodeType = "IEP"

	CurrencyCodeTypeILS CurrencyCodeType = "ILS"

	CurrencyCodeTypeITL CurrencyCodeType = "ITL"

	CurrencyCodeTypeJMD CurrencyCodeType = "JMD"

	CurrencyCodeTypeJPY CurrencyCodeType = "JPY"

	CurrencyCodeTypeJOD CurrencyCodeType = "JOD"

	CurrencyCodeTypeKZT CurrencyCodeType = "KZT"

	CurrencyCodeTypeKES CurrencyCodeType = "KES"

	CurrencyCodeTypeKWD CurrencyCodeType = "KWD"

	CurrencyCodeTypeKGS CurrencyCodeType = "KGS"

	CurrencyCodeTypeLAK CurrencyCodeType = "LAK"

	CurrencyCodeTypeLVL CurrencyCodeType = "LVL"

	CurrencyCodeTypeLBP CurrencyCodeType = "LBP"

	CurrencyCodeTypeLSL CurrencyCodeType = "LSL"

	CurrencyCodeTypeLRD CurrencyCodeType = "LRD"

	CurrencyCodeTypeLYD CurrencyCodeType = "LYD"

	CurrencyCodeTypeLTL CurrencyCodeType = "LTL"

	CurrencyCodeTypeLUF CurrencyCodeType = "LUF"

	CurrencyCodeTypeMOP CurrencyCodeType = "MOP"

	CurrencyCodeTypeMKD CurrencyCodeType = "MKD"

	CurrencyCodeTypeMGF CurrencyCodeType = "MGF"

	CurrencyCodeTypeMWK CurrencyCodeType = "MWK"

	CurrencyCodeTypeMYR CurrencyCodeType = "MYR"

	CurrencyCodeTypeMVR CurrencyCodeType = "MVR"

	CurrencyCodeTypeMTL CurrencyCodeType = "MTL"

	CurrencyCodeTypeMRO CurrencyCodeType = "MRO"

	CurrencyCodeTypeMUR CurrencyCodeType = "MUR"

	CurrencyCodeTypeMXN CurrencyCodeType = "MXN"

	CurrencyCodeTypeMDL CurrencyCodeType = "MDL"

	CurrencyCodeTypeMNT CurrencyCodeType = "MNT"

	CurrencyCodeTypeMAD CurrencyCodeType = "MAD"

	CurrencyCodeTypeMZM CurrencyCodeType = "MZM"

	CurrencyCodeTypeMMK CurrencyCodeType = "MMK"

	CurrencyCodeTypeNAD CurrencyCodeType = "NAD"

	CurrencyCodeTypeNPR CurrencyCodeType = "NPR"

	CurrencyCodeTypeANG CurrencyCodeType = "ANG"

	CurrencyCodeTypeZRN CurrencyCodeType = "ZRN"

	CurrencyCodeTypeNZD CurrencyCodeType = "NZD"

	CurrencyCodeTypeNIC CurrencyCodeType = "NIC"

	CurrencyCodeTypeNGN CurrencyCodeType = "NGN"

	CurrencyCodeTypeKPW CurrencyCodeType = "KPW"

	CurrencyCodeTypeNOK CurrencyCodeType = "NOK"

	CurrencyCodeTypePKR CurrencyCodeType = "PKR"

	CurrencyCodeTypePAB CurrencyCodeType = "PAB"

	CurrencyCodeTypePGK CurrencyCodeType = "PGK"

	CurrencyCodeTypePYG CurrencyCodeType = "PYG"

	CurrencyCodeTypePEN CurrencyCodeType = "PEN"

	CurrencyCodeTypePHP CurrencyCodeType = "PHP"

	CurrencyCodeTypePLN CurrencyCodeType = "PLN"

	CurrencyCodeTypePTE CurrencyCodeType = "PTE"

	CurrencyCodeTypeQAR CurrencyCodeType = "QAR"

	CurrencyCodeTypeOMR CurrencyCodeType = "OMR"

	CurrencyCodeTypeROL CurrencyCodeType = "ROL"

	CurrencyCodeTypeRUR CurrencyCodeType = "RUR"

	CurrencyCodeTypeRWF CurrencyCodeType = "RWF"

	CurrencyCodeTypeSTD CurrencyCodeType = "STD"

	CurrencyCodeTypeSAR CurrencyCodeType = "SAR"

	CurrencyCodeTypeSCR CurrencyCodeType = "SCR"

	CurrencyCodeTypeSLL CurrencyCodeType = "SLL"

	CurrencyCodeTypeSGD CurrencyCodeType = "SGD"

	CurrencyCodeTypeSKK CurrencyCodeType = "SKK"

	CurrencyCodeTypeSIT CurrencyCodeType = "SIT"

	CurrencyCodeTypeSBD CurrencyCodeType = "SBD"

	CurrencyCodeTypeSOS CurrencyCodeType = "SOS"

	CurrencyCodeTypeZAR CurrencyCodeType = "ZAR"

	CurrencyCodeTypeKRW CurrencyCodeType = "KRW"

	CurrencyCodeTypeESP CurrencyCodeType = "ESP"

	CurrencyCodeTypeLKR CurrencyCodeType = "LKR"

	CurrencyCodeTypeSHP CurrencyCodeType = "SHP"

	CurrencyCodeTypeGBP CurrencyCodeType = "GBP"

	CurrencyCodeTypeSDP CurrencyCodeType = "SDP"

	CurrencyCodeTypeSRG CurrencyCodeType = "SRG"

	CurrencyCodeTypeSZL CurrencyCodeType = "SZL"

	CurrencyCodeTypeSEK CurrencyCodeType = "SEK"

	CurrencyCodeTypeCHF CurrencyCodeType = "CHF"

	CurrencyCodeTypeSYP CurrencyCodeType = "SYP"

	CurrencyCodeTypeTWD CurrencyCodeType = "TWD"

	CurrencyCodeTypeTJR CurrencyCodeType = "TJR"

	CurrencyCodeTypeTZS CurrencyCodeType = "TZS"

	CurrencyCodeTypeTHB CurrencyCodeType = "THB"

	CurrencyCodeTypeTPE CurrencyCodeType = "TPE"

	CurrencyCodeTypeTOP CurrencyCodeType = "TOP"

	CurrencyCodeTypeTTD CurrencyCodeType = "TTD"

	CurrencyCodeTypeTND CurrencyCodeType = "TND"

	CurrencyCodeTypeTRL CurrencyCodeType = "TRL"

	CurrencyCodeTypeTMM CurrencyCodeType = "TMM"

	CurrencyCodeTypeAED CurrencyCodeType = "AED"

	CurrencyCodeTypeUGX CurrencyCodeType = "UGX"

	CurrencyCodeTypeUAH CurrencyCodeType = "UAH"

	CurrencyCodeTypeUYU CurrencyCodeType = "UYU"

	CurrencyCodeTypeUSD CurrencyCodeType = "USD"

	CurrencyCodeTypeUZS CurrencyCodeType = "UZS"

	CurrencyCodeTypeVUV CurrencyCodeType = "VUV"

	CurrencyCodeTypeVEB CurrencyCodeType = "VEB"

	CurrencyCodeTypeVND CurrencyCodeType = "VND"

	CurrencyCodeTypeWST CurrencyCodeType = "WST"

	CurrencyCodeTypeYER CurrencyCodeType = "YER"

	CurrencyCodeTypeYUM CurrencyCodeType = "YUM"

	CurrencyCodeTypeZMK CurrencyCodeType = "ZMK"

	CurrencyCodeTypeZWD CurrencyCodeType = "ZWD"
)

type CurrencyNumberType string

const (
	CurrencyNumberType004 CurrencyNumberType = "004"

	CurrencyNumberType008 CurrencyNumberType = "008"

	CurrencyNumberType012 CurrencyNumberType = "012"

	CurrencyNumberType024 CurrencyNumberType = "024"

	CurrencyNumberType032 CurrencyNumberType = "032"

	CurrencyNumberType051 CurrencyNumberType = "051"

	CurrencyNumberType533 CurrencyNumberType = "533"

	CurrencyNumberType036 CurrencyNumberType = "036"

	CurrencyNumberType040 CurrencyNumberType = "040"

	CurrencyNumberType031 CurrencyNumberType = "031"

	CurrencyNumberType044 CurrencyNumberType = "044"

	CurrencyNumberType048 CurrencyNumberType = "048"

	CurrencyNumberType050 CurrencyNumberType = "050"

	CurrencyNumberType052 CurrencyNumberType = "052"

	CurrencyNumberType974 CurrencyNumberType = "974"

	CurrencyNumberType056 CurrencyNumberType = "056"

	CurrencyNumberType084 CurrencyNumberType = "084"

	CurrencyNumberType060 CurrencyNumberType = "060"

	CurrencyNumberType064 CurrencyNumberType = "064"

	CurrencyNumberType068 CurrencyNumberType = "068"

	CurrencyNumberType977 CurrencyNumberType = "977"

	CurrencyNumberType072 CurrencyNumberType = "072"

	CurrencyNumberType986 CurrencyNumberType = "986"

	CurrencyNumberType096 CurrencyNumberType = "096"

	CurrencyNumberType100 CurrencyNumberType = "100"

	CurrencyNumberType108 CurrencyNumberType = "108"

	CurrencyNumberType116 CurrencyNumberType = "116"

	CurrencyNumberType124 CurrencyNumberType = "124"

	CurrencyNumberType132 CurrencyNumberType = "132"

	CurrencyNumberType136 CurrencyNumberType = "136"

	CurrencyNumberType952 CurrencyNumberType = "952"

	CurrencyNumberType950 CurrencyNumberType = "950"

	CurrencyNumberType953 CurrencyNumberType = "953"

	CurrencyNumberType152 CurrencyNumberType = "152"

	CurrencyNumberType156 CurrencyNumberType = "156"

	CurrencyNumberType170 CurrencyNumberType = "170"

	CurrencyNumberType174 CurrencyNumberType = "174"

	CurrencyNumberType976 CurrencyNumberType = "976"

	CurrencyNumberType188 CurrencyNumberType = "188"

	CurrencyNumberType191 CurrencyNumberType = "191"

	CurrencyNumberType192 CurrencyNumberType = "192"

	CurrencyNumberType196 CurrencyNumberType = "196"

	CurrencyNumberType203 CurrencyNumberType = "203"

	CurrencyNumberType208 CurrencyNumberType = "208"

	CurrencyNumberType276 CurrencyNumberType = "276"

	CurrencyNumberType262 CurrencyNumberType = "262"

	CurrencyNumberType214 CurrencyNumberType = "214"

	CurrencyNumberType528 CurrencyNumberType = "528"

	CurrencyNumberType951 CurrencyNumberType = "951"

	CurrencyNumberType218 CurrencyNumberType = "218"

	CurrencyNumberType818 CurrencyNumberType = "818"

	CurrencyNumberType222 CurrencyNumberType = "222"

	CurrencyNumberType232 CurrencyNumberType = "232"

	CurrencyNumberType233 CurrencyNumberType = "233"

	CurrencyNumberType230 CurrencyNumberType = "230"

	CurrencyNumberType978 CurrencyNumberType = "978"

	CurrencyNumberType238 CurrencyNumberType = "238"

	CurrencyNumberType242 CurrencyNumberType = "242"

	CurrencyNumberType246 CurrencyNumberType = "246"

	CurrencyNumberType250 CurrencyNumberType = "250"

	CurrencyNumberType270 CurrencyNumberType = "270"

	CurrencyNumberType268 CurrencyNumberType = "268"

	CurrencyNumberType288 CurrencyNumberType = "288"

	CurrencyNumberType292 CurrencyNumberType = "292"

	CurrencyNumberType300 CurrencyNumberType = "300"

	CurrencyNumberType320 CurrencyNumberType = "320"

	CurrencyNumberType328 CurrencyNumberType = "328"

	CurrencyNumberType332 CurrencyNumberType = "332"

	CurrencyNumberType340 CurrencyNumberType = "340"

	CurrencyNumberType344 CurrencyNumberType = "344"

	CurrencyNumberType348 CurrencyNumberType = "348"

	CurrencyNumberType352 CurrencyNumberType = "352"

	CurrencyNumberType356 CurrencyNumberType = "356"

	CurrencyNumberType360 CurrencyNumberType = "360"

	CurrencyNumberType364 CurrencyNumberType = "364"

	CurrencyNumberType368 CurrencyNumberType = "368"

	CurrencyNumberType372 CurrencyNumberType = "372"

	CurrencyNumberType376 CurrencyNumberType = "376"

	CurrencyNumberType380 CurrencyNumberType = "380"

	CurrencyNumberType388 CurrencyNumberType = "388"

	CurrencyNumberType392 CurrencyNumberType = "392"

	CurrencyNumberType400 CurrencyNumberType = "400"

	CurrencyNumberType398 CurrencyNumberType = "398"

	CurrencyNumberType404 CurrencyNumberType = "404"

	CurrencyNumberType414 CurrencyNumberType = "414"

	CurrencyNumberType417 CurrencyNumberType = "417"

	CurrencyNumberType418 CurrencyNumberType = "418"

	CurrencyNumberType428 CurrencyNumberType = "428"

	CurrencyNumberType422 CurrencyNumberType = "422"

	CurrencyNumberType426 CurrencyNumberType = "426"

	CurrencyNumberType430 CurrencyNumberType = "430"

	CurrencyNumberType434 CurrencyNumberType = "434"

	CurrencyNumberType440 CurrencyNumberType = "440"

	CurrencyNumberType442 CurrencyNumberType = "442"

	CurrencyNumberType446 CurrencyNumberType = "446"

	CurrencyNumberType807 CurrencyNumberType = "807"

	CurrencyNumberType450 CurrencyNumberType = "450"

	CurrencyNumberType454 CurrencyNumberType = "454"

	CurrencyNumberType458 CurrencyNumberType = "458"

	CurrencyNumberType462 CurrencyNumberType = "462"

	CurrencyNumberType470 CurrencyNumberType = "470"

	CurrencyNumberType478 CurrencyNumberType = "478"

	CurrencyNumberType480 CurrencyNumberType = "480"

	CurrencyNumberType484 CurrencyNumberType = "484"

	CurrencyNumberType498 CurrencyNumberType = "498"

	CurrencyNumberType496 CurrencyNumberType = "496"

	CurrencyNumberType504 CurrencyNumberType = "504"

	CurrencyNumberType508 CurrencyNumberType = "508"

	CurrencyNumberType104 CurrencyNumberType = "104"

	CurrencyNumberType516 CurrencyNumberType = "516"

	CurrencyNumberType524 CurrencyNumberType = "524"

	CurrencyNumberType532 CurrencyNumberType = "532"

	CurrencyNumberType186 CurrencyNumberType = "186"

	CurrencyNumberType554 CurrencyNumberType = "554"

	CurrencyNumberType558 CurrencyNumberType = "558"

	CurrencyNumberType566 CurrencyNumberType = "566"

	CurrencyNumberType408 CurrencyNumberType = "408"

	CurrencyNumberType578 CurrencyNumberType = "578"

	CurrencyNumberType586 CurrencyNumberType = "586"

	CurrencyNumberType590 CurrencyNumberType = "590"

	CurrencyNumberType598 CurrencyNumberType = "598"

	CurrencyNumberType600 CurrencyNumberType = "600"

	CurrencyNumberType604 CurrencyNumberType = "604"

	CurrencyNumberType608 CurrencyNumberType = "608"

	CurrencyNumberType985 CurrencyNumberType = "985"

	CurrencyNumberType620 CurrencyNumberType = "620"

	CurrencyNumberType634 CurrencyNumberType = "634"

	CurrencyNumberType512 CurrencyNumberType = "512"

	CurrencyNumberType642 CurrencyNumberType = "642"

	CurrencyNumberType810 CurrencyNumberType = "810"

	CurrencyNumberType646 CurrencyNumberType = "646"

	CurrencyNumberType678 CurrencyNumberType = "678"

	CurrencyNumberType682 CurrencyNumberType = "682"

	CurrencyNumberType690 CurrencyNumberType = "690"

	CurrencyNumberType694 CurrencyNumberType = "694"

	CurrencyNumberType702 CurrencyNumberType = "702"

	CurrencyNumberType703 CurrencyNumberType = "703"

	CurrencyNumberType705 CurrencyNumberType = "705"

	CurrencyNumberType090 CurrencyNumberType = "090"

	CurrencyNumberType706 CurrencyNumberType = "706"

	CurrencyNumberType710 CurrencyNumberType = "710"

	CurrencyNumberType410 CurrencyNumberType = "410"

	CurrencyNumberType724 CurrencyNumberType = "724"

	CurrencyNumberType144 CurrencyNumberType = "144"

	CurrencyNumberType654 CurrencyNumberType = "654"

	CurrencyNumberType826 CurrencyNumberType = "826"

	CurrencyNumberType736 CurrencyNumberType = "736"

	CurrencyNumberType740 CurrencyNumberType = "740"

	CurrencyNumberType748 CurrencyNumberType = "748"

	CurrencyNumberType752 CurrencyNumberType = "752"

	CurrencyNumberType756 CurrencyNumberType = "756"

	CurrencyNumberType760 CurrencyNumberType = "760"

	CurrencyNumberType901 CurrencyNumberType = "901"

	CurrencyNumberType762 CurrencyNumberType = "762"

	CurrencyNumberType834 CurrencyNumberType = "834"

	CurrencyNumberType764 CurrencyNumberType = "764"

	CurrencyNumberType626 CurrencyNumberType = "626"

	CurrencyNumberType776 CurrencyNumberType = "776"

	CurrencyNumberType780 CurrencyNumberType = "780"

	CurrencyNumberType788 CurrencyNumberType = "788"

	CurrencyNumberType792 CurrencyNumberType = "792"

	CurrencyNumberType795 CurrencyNumberType = "795"

	CurrencyNumberType784 CurrencyNumberType = "784"

	CurrencyNumberType800 CurrencyNumberType = "800"

	CurrencyNumberType980 CurrencyNumberType = "980"

	CurrencyNumberType858 CurrencyNumberType = "858"

	CurrencyNumberType840 CurrencyNumberType = "840"

	CurrencyNumberType860 CurrencyNumberType = "860"

	CurrencyNumberType548 CurrencyNumberType = "548"

	CurrencyNumberType862 CurrencyNumberType = "862"

	CurrencyNumberType704 CurrencyNumberType = "704"

	CurrencyNumberType882 CurrencyNumberType = "882"

	CurrencyNumberType886 CurrencyNumberType = "886"

	CurrencyNumberType891 CurrencyNumberType = "891"

	CurrencyNumberType894 CurrencyNumberType = "894"

	CurrencyNumberType716 CurrencyNumberType = "716"
)

// The type of charge

type ChargeTypeType string

const (
	ChargeTypeTypeOrder ChargeTypeType = "Order"

	ChargeTypeTypeRun ChargeTypeType = "Run"

	ChargeTypeTypeSetup ChargeTypeType = "Setup"
)

// The type of decoration UOM

type DecorationUomType string

const (
	DecorationUomTypeColors DecorationUomType = "Colors"

	DecorationUomTypeInches DecorationUomType = "Inches"

	DecorationUomTypeLocations DecorationUomType = "Locations"

	DecorationUomTypeOther DecorationUomType = "Other"

	DecorationUomTypeStitches DecorationUomType = "Stitches"

	DecorationUomTypeSquareInches DecorationUomType = "SquareInches"
)

// The type of Quantity UOM

type QuantityUomType string

const (
	QuantityUomTypeBX QuantityUomType = "BX"

	QuantityUomTypeCA QuantityUomType = "CA"

	QuantityUomTypeDZ QuantityUomType = "DZ"

	QuantityUomTypeEA QuantityUomType = "EA"

	QuantityUomTypeKT QuantityUomType = "KT"

	QuantityUomTypePR QuantityUomType = "PR"

	QuantityUomTypePK QuantityUomType = "PK"

	QuantityUomTypeRL QuantityUomType = "RL"

	QuantityUomTypeST QuantityUomType = "ST"

	QuantityUomTypeSL QuantityUomType = "SL"

	QuantityUomTypeTH QuantityUomType = "TH"
)

type DimensionUomEnum string

const (
	DimensionUomEnumMM DimensionUomEnum = "MM"

	DimensionUomEnumCM DimensionUomEnum = "CM"

	DimensionUomEnumMR DimensionUomEnum = "MR"

	DimensionUomEnumIN DimensionUomEnum = "IN"

	DimensionUomEnumFT DimensionUomEnum = "FT"

	DimensionUomEnumYD DimensionUomEnum = "YD"
)

type WeightUomEnum string

const (
	WeightUomEnumME WeightUomEnum = "ME"

	WeightUomEnumKG WeightUomEnum = "KG"

	WeightUomEnumOZ WeightUomEnum = "OZ"

	WeightUomEnumLB WeightUomEnum = "LB"
)

type ErrorMessage struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ ErrorMessage"`

	//
	// Response for any error requiring notification to requestor
	//
	Code int32 `xml:"code,omitempty" json:"code,omitempty"`

	//
	// Response for any error requiring notification to requestor

	Description string `xml:"description,omitempty" json:"description,omitempty"`
}

type ChargeId int32

type DecorationId int32

type LocationId int32

type PartGroup int32

type NextPartGroup int32

type DefaultPart bool

type MaxDecoration int32

type MinDecoration int32

type DecorationUnitsMax int32

type LocationRank int32

type Currency CurrencyCodeType

type FobArray struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ FobArray"`

	Fob []struct {
		FobId *string `xml:"fobId,omitempty" json:"fobId,omitempty"`

		FobPostalCode *string `xml:"fobPostalCode,omitempty" json:"fobPostalCode,omitempty"`
	} `xml:"Fob,omitempty" json:"Fob,omitempty"`
}

type GetAvailableLocationsRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetAvailableLocationsRequest"`

	WsVersion *string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *string `xml:"id,omitempty" json:"id,omitempty"`

	Password *string `xml:"password,omitempty" json:"password,omitempty"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

	LocalizationCountry *string `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *string `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`
}

type AvailableLocation struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ AvailableLocation"`

	LocationId *LocationId `xml:"locationId,omitempty" json:"locationId,omitempty"`

	LocationName *string `xml:"locationName,omitempty" json:"locationName,omitempty"`
}

type GetAvailableLocationsResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetAvailableLocationsResponse"`

	AvailableLocationArray struct {
		AvailableLocation []*AvailableLocation `xml:"AvailableLocation,omitempty" json:"AvailableLocation,omitempty"`
	} `xml:"AvailableLocationArray,omitempty" json:"AvailableLocationArray,omitempty"`

	ErrorMessage *ErrorMessage `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`
}

type GetDecorationColorsRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetDecorationColorsRequest"`

	WsVersion *string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *string `xml:"id,omitempty" json:"id,omitempty"`

	Password *string `xml:"password,omitempty" json:"password,omitempty"`

	LocationId *LocationId `xml:"locationId,omitempty" json:"locationId,omitempty"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

	DecorationId *DecorationId `xml:"decorationId,omitempty" json:"decorationId,omitempty"`

	LocalizationCountry *string `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *string `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`
}

type Color struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Color"`

	ColorId *string `xml:"colorId,omitempty" json:"colorId,omitempty"`

	ColorName *string `xml:"colorName,omitempty" json:"colorName,omitempty"`
}

type DecorationMethod struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ DecorationMethod"`

	DecorationId *DecorationId `xml:"decorationId,omitempty" json:"decorationId,omitempty"`

	DecorationName *string `xml:"decorationName,omitempty" json:"decorationName,omitempty"`
}

type GetDecorationColorsResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetDecorationColorsResponse"`

	DecorationColors struct {
		ColorArray struct {
			Color []*Color `xml:"Color,omitempty" json:"Color,omitempty"`
		} `xml:"ColorArray,omitempty" json:"ColorArray,omitempty"`

		ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

		LocationId *LocationId `xml:"locationId,omitempty" json:"locationId,omitempty"`

		DecorationMethodArray struct {
			DecorationMethod []*DecorationMethod `xml:"DecorationMethod,omitempty" json:"DecorationMethod,omitempty"`
		} `xml:"DecorationMethodArray,omitempty" json:"DecorationMethodArray,omitempty"`

		//
		// PMS match or nto
		//
		PmsMatch bool `xml:"pmsMatch,omitempty" json:"pmsMatch,omitempty"`

		//
		// Full Color or not
		//
		FullColor bool `xml:"fullColor,omitempty" json:"fullColor,omitempty"`
	} `xml:"DecorationColors,omitempty" json:"DecorationColors,omitempty"`

	ErrorMessage *ErrorMessage `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`
}

type GetFobPointsRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetFobPointsRequest"`

	WsVersion *string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *string `xml:"id,omitempty" json:"id,omitempty"`

	Password *string `xml:"password,omitempty" json:"password,omitempty"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

	LocalizationCountry *string `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *string `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`
}

type FobPoint struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ FobPoint"`

	FobId *string `xml:"fobId,omitempty" json:"fobId,omitempty"`

	//
	// The fob city
	//

	FobCity string `xml:"fobCity,omitempty" json:"fobCity,omitempty"`

	//
	// The fob state
	//

	FobState string `xml:"fobState,omitempty" json:"fobState,omitempty"`

	FobPostalCode *string `xml:"fobPostalCode,omitempty" json:"fobPostalCode,omitempty"`

	//
	// The fob country
	//

	FobCountry string `xml:"fobCountry,omitempty" json:"fobCountry,omitempty"`

	CurrencySupportedArray struct {
		CurrencySupported []*CurrencySupported `xml:"CurrencySupported,omitempty" json:"CurrencySupported,omitempty"`
	} `xml:"CurrencySupportedArray,omitempty" json:"CurrencySupportedArray,omitempty"`

	ProductArray struct {
		Product []*Product `xml:"Product,omitempty" json:"Product,omitempty"`
	} `xml:"ProductArray,omitempty" json:"ProductArray,omitempty"`
}

type CurrencySupported struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ CurrencySupported"`

	Currency *Currency `xml:"currency,omitempty" json:"currency,omitempty"`
}

type Product struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Product"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`
}

type GetFobPointsResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetFobPointsResponse"`

	FobPointArray struct {
		FobPoint []*FobPoint `xml:"FobPoint,omitempty" json:"FobPoint,omitempty"`
	} `xml:"FobPointArray,omitempty" json:"FobPointArray,omitempty"`

	ErrorMessage *ErrorMessage `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`
}

type GetAvailableChargesRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetAvailableChargesRequest"`

	WsVersion *string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *string `xml:"id,omitempty" json:"id,omitempty"`

	Password *string `xml:"password,omitempty" json:"password,omitempty"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

	LocalizationCountry *string `xml:"localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *string `xml:"localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`
}

type AvailableCharge struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ AvailableCharge"`

	ChargeId *ChargeId `xml:"chargeId,omitempty" json:"chargeId,omitempty"`

	ChargeName *string `xml:"chargeName,omitempty" json:"chargeName,omitempty"`

	ChargeDescription *string `xml:"chargeDescription,omitempty" json:"chargeDescription,omitempty"`

	ChargeType *string `xml:"chargeType,omitempty" json:"chargeType,omitempty"`
}

type GetAvailableChargesResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetAvailableChargesResponse"`

	AvailableChargeArray struct {
		AvailableCharge []*AvailableCharge `xml:"AvailableCharge,omitempty" json:"AvailableCharge,omitempty"`
	} `xml:"AvailableChargeArray,omitempty" json:"AvailableChargeArray,omitempty"`

	ErrorMessage *ErrorMessage `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`
}

type GetConfigurationAndPricingRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetConfigurationAndPricingRequest"`

	WsVersion *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ wsVersion,omitempty" json:"wsVersion,omitempty"`

	Id *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ id,omitempty" json:"id,omitempty"`

	Password *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ password,omitempty" json:"password,omitempty"`

	ProductId *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ productId,omitempty" json:"productId,omitempty"`

	PartId *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ partId,omitempty" json:"partId,omitempty"`

	Currency *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ currency,omitempty" json:"currency,omitempty"`

	FobId *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ fobId,omitempty" json:"fobId,omitempty"`

	PriceType *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ priceType,omitempty" json:"priceType,omitempty"`

	LocalizationCountry *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ localizationCountry,omitempty" json:"localizationCountry,omitempty"`

	LocalizationLanguage *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ localizationLanguage,omitempty" json:"localizationLanguage,omitempty"`

	ConfigurationType *string `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/SharedObjects/ configurationType,omitempty" json:"configurationType,omitempty"`
}

type Part struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Part"`

	PartId *string `xml:"partId,omitempty" json:"partId,omitempty"`

	PartDescription *string `xml:"partDescription,omitempty" json:"partDescription,omitempty"`

	PartPriceArray struct {
		PartPrice []*PartPrice `xml:"PartPrice,omitempty" json:"PartPrice,omitempty"`
	} `xml:"PartPriceArray,omitempty" json:"PartPriceArray,omitempty"`

	PartGroup *PartGroup `xml:"partGroup,omitempty" json:"partGroup,omitempty"`

	NextPartGroup *NextPartGroup `xml:"nextPartGroup,omitempty" json:"nextPartGroup,omitempty"`

	PartGroupRequired *string `xml:"partGroupRequired,omitempty" json:"partGroupRequired,omitempty"`

	PartGroupDescription *string `xml:"partGroupDescription,omitempty" json:"partGroupDescription,omitempty"`

	Ratio *string `xml:"ratio,omitempty" json:"ratio,omitempty"`

	DefaultPart *DefaultPart `xml:"defaultPart,omitempty" json:"defaultPart,omitempty"`

	LocationIdArray struct {
		LocationId []struct {
			LocationId *LocationId `xml:"locationId,omitempty" json:"locationId,omitempty"`
		} `xml:"LocationId,omitempty" json:"LocationId,omitempty"`
	} `xml:"LocationIdArray,omitempty" json:"LocationIdArray,omitempty"`
}

type PartPrice struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ PartPrice"`

	// The minimum quantity
	MinQuantity int32 `xml:"minQuantity,omitempty" json:"minQuantity,omitempty"`

	// The price

	Price float64 `xml:"price,omitempty" json:"price,omitempty"`

	// The discount code

	DiscountCode string `xml:"discountCode,omitempty" json:"discountCode,omitempty"`

	// Enumerated list of unit of measure used to describe the price

	PriceUom *QuantityUomType `xml:"priceUom,omitempty" json:"priceUom,omitempty"`

	// The price effective date
	PriceEffectiveDate CustomTime `xml:"priceEffectiveDate,omitempty" json:"priceEffectiveDate,omitempty"`

	// The price expiry date
	PriceExpiryDate CustomTime `xml:"priceExpiryDate,omitempty" json:"priceExpiryDate,omitempty"`
}

type Location struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Location"`

	LocationId *int `xml:"locationId,omitempty" json:"locationId,omitempty"`

	LocationName *string `xml:"locationName,omitempty" json:"locationName,omitempty"`

	DecorationArray struct {
		Decoration []*Decoration `xml:"Decoration,omitempty" json:"Decoration,omitempty"`
	} `xml:"DecorationArray,omitempty" json:"DecorationArray,omitempty"`

	DecorationsIncluded *string `xml:"decorationsIncluded,omitempty" json:"decorationsIncluded,omitempty"`

	DefaultLocation *string `xml:"defaultLocation,omitempty" json:"defaultLocation,omitempty"`

	MaxDecoration *int `xml:"maxDecoration,omitempty" json:"maxDecoration,omitempty"`

	MinDecoration *int `xml:"minDecoration,omitempty" json:"minDecoration,omitempty"`

	LocationRank *int `xml:"locationRank,omitempty" json:"locationRank,omitempty"`
}

type Decoration struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Decoration"`

	DecorationId *int `xml:"decorationId,omitempty" json:"decorationId,omitempty"`

	DecorationName *string `xml:"decorationName,omitempty" json:"decorationName,omitempty"`

	DecorationGeometry *string `xml:"decorationGeometry,omitempty" json:"decorationGeometry,omitempty"`

	DecorationHeight *string `xml:"decorationHeight,omitempty" json:"decorationHeight,omitempty"`

	DecorationWidth *string `xml:"decorationWidth,omitempty" json:"decorationWidth,omitempty"`

	DecorationDiameter *string `xml:"decorationDiameter,omitempty" json:"decorationDiameter,omitempty"`

	DecorationUom *string `xml:"decorationUom,omitempty" json:"decorationUom,omitempty"`

	//
	// Buyer is allowed to substitute a decoration location without changing the price
	//
	AllowSubForDefaultLocation bool `xml:"allowSubForDefaultLocation,omitempty" json:"allowSubForDefaultLocation,omitempty"`

	//
	// Buyer is allowed to substitute a decoration method without changing the price
	//
	AllowSubForDefaultMethod bool `xml:"allowSubForDefaultMethod,omitempty" json:"allowSubForDefaultMethod,omitempty"`

	//
	// Specifies the Part Quantity where the Less than Minimum (LTM) Setup Charge Applies.
	//
	ItemPartQuantityLTM int32 `xml:"itemPartQuantityLTM,omitempty" json:"itemPartQuantityLTM,omitempty"`

	ChargeArray struct {
		Charge []*Charge `xml:"Charge,omitempty" json:"Charge,omitempty"`
	} `xml:"ChargeArray,omitempty" json:"ChargeArray,omitempty"`

	// The number of included decoration units.
	DecorationUnitsIncluded int32 `xml:"decorationUnitsIncluded,omitempty" json:"decorationUnitsIncluded,omitempty"`

	DecorationUnitsIncludedUom *string `xml:"decorationUnitsIncludedUom,omitempty" json:"decorationUnitsIncludedUom,omitempty"`

	DecorationUnitsMax *int `xml:"decorationUnitsMax,omitempty" json:"decorationUnitsMax,omitempty"`

	//
	// The default decoration
	//
	DefaultDecoration bool `xml:"defaultDecoration,omitempty" json:"defaultDecoration,omitempty"`

	// Lead Time
	LeadTime int32 `xml:"leadTime,omitempty" json:"leadTime,omitempty"`

	// Rush Lead Time
	RushLeadTime int32 `xml:"rushLeadTime,omitempty" json:"rushLeadTime,omitempty"`
}

type Charge struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Charge"`

	ChargeId *ChargeId `xml:"chargeId,omitempty" json:"chargeId,omitempty"`

	ChargeName *string `xml:"chargeName,omitempty" json:"chargeName,omitempty"`

	ChargeDescription *string `xml:"chargeDescription,omitempty" json:"chargeDescription,omitempty"`

	ChargeType *string `xml:"chargeType,omitempty" json:"chargeType,omitempty"`

	ChargePriceArray struct {
		ChargePrice []*ChargePrice `xml:"ChargePrice,omitempty" json:"ChargePrice,omitempty"`
	} `xml:"ChargePriceArray,omitempty" json:"ChargePriceArray,omitempty"`

	//
	// The charges applies LTM
	//
	ChargesAppliesLTM bool `xml:"chargesAppliesLTM,omitempty" json:"chargesAppliesLTM,omitempty"`

	//
	// The number of times a charge will occur per location
	ChargesPerLocation int32 `xml:"chargesPerLocation,omitempty" json:"chargesPerLocation,omitempty"`

	//
	// The number of times a charge will occur per color
	ChargesPerColor int32 `xml:"chargesPerColor,omitempty" json:"chargesPerColor,omitempty"`
}

type ChargePrice struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ ChargePrice"`

	//
	// The minimum quantity x grid
	//
	XMinQty int32 `xml:"xMinQty,omitempty" json:"xMinQty,omitempty"`

	// The x grid uom

	XUom *QuantityUomType `xml:"xUom,omitempty" json:"xUom,omitempty"`

	// The minimum quantity y grid
	YMinQty int32 `xml:"yMinQty,omitempty" json:"yMinQty,omitempty"`

	// The y grid uom
	YUom *DecorationUomType `xml:"yUom,omitempty" json:"yUom,omitempty"`

	//
	// The price
	//

	Price float64 `xml:"price,omitempty" json:"price,omitempty"`

	// The discount code

	DiscountCode string `xml:"discountCode,omitempty" json:"discountCode,omitempty"`

	// repeat price

	RepeatPrice float64 `xml:"repeatPrice,omitempty" json:"repeatPrice,omitempty"`

	// The repeat discount code

	RepeatDiscountCode string `xml:"repeatDiscountCode,omitempty" json:"repeatDiscountCode,omitempty"`

	// The price effective date
	PriceEffectiveDate CustomTime `xml:"priceEffectiveDate,omitempty" json:"priceEffectiveDate,omitempty"`

	// The price expiry date
	PriceExpiryDate CustomTime `xml:"priceExpiryDate,omitempty" json:"priceExpiryDate,omitempty"`
}

type Configuration struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ Configuration"`

	PartArray struct {
		Part []*Part `xml:"Part,omitempty" json:"Part,omitempty"`
	} `xml:"PartArray,omitempty" json:"PartArray,omitempty"`

	LocationArray struct {
		Location []*Location `xml:"Location,omitempty" json:"Location,omitempty"`
	} `xml:"LocationArray,omitempty" json:"LocationArray,omitempty"`

	ProductId *string `xml:"productId,omitempty" json:"productId,omitempty"`

	Currency *Currency `xml:"currency,omitempty" json:"currency,omitempty"`

	FobArray *FobArray `xml:"FobArray,omitempty" json:"FobArray,omitempty"`

	PriceType *string `xml:"priceType,omitempty" json:"priceType,omitempty"`
}

type GetConfigurationAndPricingResponse struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/ GetConfigurationAndPricingResponse"`

	Configuration *Configuration `xml:"Configuration,omitempty" json:"Configuration,omitempty"`

	ErrorMessage *ErrorMessage `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`
}

type PricingAndConfigurationService interface {
	GetAvailableLocations(request *GetAvailableLocationsRequest) (*GetAvailableLocationsResponse, error)

	GetAvailableLocationsContext(ctx context.Context, request *GetAvailableLocationsRequest) (*GetAvailableLocationsResponse, error)

	GetDecorationColors(request *GetDecorationColorsRequest) (*GetDecorationColorsResponse, error)

	GetDecorationColorsContext(ctx context.Context, request *GetDecorationColorsRequest) (*GetDecorationColorsResponse, error)

	GetFobPoints(request *GetFobPointsRequest) (*GetFobPointsResponse, error)

	GetFobPointsContext(ctx context.Context, request *GetFobPointsRequest) (*GetFobPointsResponse, error)

	GetAvailableCharges(request *GetAvailableChargesRequest) (*GetAvailableChargesResponse, error)

	GetAvailableChargesContext(ctx context.Context, request *GetAvailableChargesRequest) (*GetAvailableChargesResponse, error)

	GetConfigurationAndPricing(request *GetConfigurationAndPricingRequest) (*GetConfigurationAndPricingResponse, error)

	GetConfigurationAndPricingContext(ctx context.Context, request *GetConfigurationAndPricingRequest) (*GetConfigurationAndPricingResponse, error)
}

type pricingAndConfigurationService struct {
	client *soap.Client
}

func NewPricingAndConfigurationService(client *soap.Client) PricingAndConfigurationService {
	return &pricingAndConfigurationService{
		client: client,
	}
}

func (service *pricingAndConfigurationService) GetAvailableLocationsContext(ctx context.Context, request *GetAvailableLocationsRequest) (*GetAvailableLocationsResponse, error) {
	response := new(GetAvailableLocationsResponse)
	err := service.client.CallContext(ctx, "getAvailableLocations", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *pricingAndConfigurationService) GetAvailableLocations(request *GetAvailableLocationsRequest) (*GetAvailableLocationsResponse, error) {
	return service.GetAvailableLocationsContext(
		context.Background(),
		request,
	)
}

func (service *pricingAndConfigurationService) GetDecorationColorsContext(ctx context.Context, request *GetDecorationColorsRequest) (*GetDecorationColorsResponse, error) {
	response := new(GetDecorationColorsResponse)
	err := service.client.CallContext(ctx, "getDecorationColors", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *pricingAndConfigurationService) GetDecorationColors(request *GetDecorationColorsRequest) (*GetDecorationColorsResponse, error) {
	return service.GetDecorationColorsContext(
		context.Background(),
		request,
	)
}

func (service *pricingAndConfigurationService) GetFobPointsContext(ctx context.Context, request *GetFobPointsRequest) (*GetFobPointsResponse, error) {
	response := new(GetFobPointsResponse)
	err := service.client.CallContext(ctx, "getFobPoints", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *pricingAndConfigurationService) GetFobPoints(request *GetFobPointsRequest) (*GetFobPointsResponse, error) {
	return service.GetFobPointsContext(
		context.Background(),
		request,
	)
}

func (service *pricingAndConfigurationService) GetAvailableChargesContext(ctx context.Context, request *GetAvailableChargesRequest) (*GetAvailableChargesResponse, error) {
	response := new(GetAvailableChargesResponse)
	err := service.client.CallContext(ctx, "getAvailableCharges", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *pricingAndConfigurationService) GetAvailableCharges(request *GetAvailableChargesRequest) (*GetAvailableChargesResponse, error) {
	return service.GetAvailableChargesContext(
		context.Background(),
		request,
	)
}

func (service *pricingAndConfigurationService) GetConfigurationAndPricingContext(ctx context.Context, request *GetConfigurationAndPricingRequest) (*GetConfigurationAndPricingResponse, error) {
	response := new(GetConfigurationAndPricingResponse)
	err := service.client.CallContext(ctx, "getConfigurationAndPricing", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *pricingAndConfigurationService) GetConfigurationAndPricing(request *GetConfigurationAndPricingRequest) (*GetConfigurationAndPricingResponse, error) {
	return service.GetConfigurationAndPricingContext(
		context.Background(),
		request,
	)
}
