// Code generated by gowsdl DO NOT EDIT.

package myservice

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type GetFilterValuesRequest struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/InventoryService/1.0.0/ GetFilterValuesRequest"`

	//
	// The Standard Version of the Web Service being referenced
	//

	WsVersion string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	//
	// The customerID or any other agreed upon ID
	//

	Id string `xml:"id,omitempty" json:"id,omitempty"`

	//
	// The password associated with the customerID
	//

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	//
	// Item’s ID
	//

	ProductID string `xml:"productID,omitempty" json:"productID,omitempty"`

	//
	// productID type (Distributor, Supplier)
	//

	ProductIDtype string `xml:"productIDtype,omitempty" json:"productIDtype,omitempty"`
}

type GetFilterValuesReply struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/InventoryService/1.0.0/ GetFilterValuesReply"`

	//
	// The associated product
	//

	ProductID string `xml:"productID,omitempty" json:"productID,omitempty"`

	FilterColorArray struct {
		FilterColor string `xml:"filterColor,omitempty" json:"filterColor,omitempty"`
	} `xml:"FilterColorArray,omitempty" json:"FilterColorArray,omitempty"`

	FilterSizeArray struct {
		FilterSize string `xml:"filterSize,omitempty" json:"filterSize,omitempty"`
	} `xml:"FilterSizeArray,omitempty" json:"FilterSizeArray,omitempty"`

	FilterSelectionArray struct {
		FilterSelection string `xml:"filterSelection,omitempty" json:"filterSelection,omitempty"`
	} `xml:"FilterSelectionArray,omitempty" json:"FilterSelectionArray,omitempty"`

	//
	// Response for any error requiring notification to requestor
	//

	ErrorMessage string `xml:"errorMessage,omitempty" json:"errorMessage,omitempty"`
}

type Request struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/InventoryService/1.0.0/ Request"`

	//
	// The Standard Version of the Web Service being referenced
	//

	WsVersion string `xml:"wsVersion,omitempty" json:"wsVersion,omitempty"`

	//
	// The customerID or any other agreed upon ID
	//

	Id string `xml:"id,omitempty" json:"id,omitempty"`

	//
	// The password associated with the customerID
	//

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	//
	// Item’s ID
	//

	ProductID string `xml:"productID,omitempty" json:"productID,omitempty"`

	//
	// productID type (Distributor, Supplier)
	//

	ProductIDtype string `xml:"productIDtype,omitempty" json:"productIDtype,omitempty"`

	FilterColorArray struct {
		FilterColor string `xml:"filterColor,omitempty" json:"filterColor,omitempty"`
	} `xml:"FilterColorArray,omitempty" json:"FilterColorArray,omitempty"`

	FilterSizeArray struct {
		FilterSize string `xml:"filterSize,omitempty" json:"filterSize,omitempty"`
	} `xml:"FilterSizeArray,omitempty" json:"FilterSizeArray,omitempty"`

	FilterSelectionArray struct {
		FilterSelection string `xml:"filterSelection,omitempty" json:"filterSelection,omitempty"`
	} `xml:"FilterSelectionArray,omitempty" json:"FilterSelectionArray,omitempty"`
}

type Reply struct {
	XMLName xml.Name `xml:"http://www.promostandards.org/WSDL/InventoryService/1.0.0/ Reply"`

	//
	// The associated product
	//

	ProductID string `xml:"productID,omitempty" json:"productID,omitempty"`

	ProductVariationInventoryArray struct {
		ProductVariationInventory []struct {

			//
			// The associated part
			//

			PartID string `xml:"partID,omitempty" json:"partID,omitempty"`

			//
			// Part’s description
			//

			PartDescription string `xml:"partDescription,omitempty" json:"partDescription,omitempty"`

			//
			// Part’s brand
			//

			PartBrand string `xml:"partBrand,omitempty" json:"partBrand,omitempty"`

			//
			// Variance from requested part’s price
			//

			PriceVariance string `xml:"priceVariance,omitempty" json:"priceVariance,omitempty"`

			//
			// The quantity available
			//

			QuantityAvailable string `xml:"quantityAvailable,omitempty" json:"quantityAvailable,omitempty"`

			//
			// Description of the color of the part
			//

			AttributeColor string `xml:"attributeColor,omitempty" json:"attributeColor,omitempty"`

			//
			// Description of the size of the part
			//

			AttributeSize string `xml:"attributeSize,omitempty" json:"attributeSize,omitempty"`

			//
			// Description of the generic selection criteria
			//

			AttributeSelection string `xml:"attributeSelection,omitempty" json:"attributeSelection,omitempty"`

			AttributeFlexArray struct {
				AttributeFlex []struct {
					Id string `xml:"id,omitempty" json:"id,omitempty"`

					Name string `xml:"name,omitempty" json:"name,omitempty"`

					Value string `xml:"value,omitempty" json:"value,omitempty"`
				} `xml:"AttributeFlex,omitempty" json:"AttributeFlex,omitempty"`
			} `xml:"AttributeFlexArray,omitempty" json:"AttributeFlexArray,omitempty"`

			//
			// customProductMessage5 Message from the supplier regarding the stock
			//

			CustomProductMessage string `xml:"customProductMessage,omitempty" json:"customProductMessage,omitempty"`

			//
			// Record type (exact, alternate)
			//

			EntryType string `xml:"entryType,omitempty" json:"entryType,omitempty"`

			//
			// Datetime inventory is available
			//
			ValidTimestamp time.Time `xml:"validTimestamp,omitempty" json:"validTimestamp,omitempty"`
		} `xml:"ProductVariationInventory,omitempty" json:"ProductVariationInventory,omitempty"`
	} `xml:"ProductVariationInventoryArray,omitempty" json:"ProductVariationInventoryArray,omitempty"`

	ProductCompanionInventoryArray struct {
		ProductCompanionInventory []struct {

			//
			// The companion part
			//

			PartID string `xml:"partID,omitempty" json:"partID,omitempty"`

			//
			// Part’s description
			//

			PartDescription string `xml:"partDescription,omitempty" json:"partDescription,omitempty"`

			//
			// Part’s brand
			//

			PartBrand string `xml:"partBrand,omitempty" json:"partBrand,omitempty"`

			//
			// Companion item price
			//

			Price string `xml:"price,omitempty" json:"price,omitempty"`

			//
			// The quantity available
			//

			QuantityAvailable string `xml:"quantityAvailable,omitempty" json:"quantityAvailable,omitempty"`

			//
			// Description of the color of the part
			//

			AttributeColor string `xml:"attributeColor,omitempty" json:"attributeColor,omitempty"`

			//
			// Description of the size of the part
			//

			AttributeSize string `xml:"attributeSize,omitempty" json:"attributeSize,omitempty"`

			//
			// Description of the generic selection criteria of the part
			//

			AttributeSelection string `xml:"attributeSelection,omitempty" json:"attributeSelection,omitempty"`

			AttributeFlexArray struct {
				AttributeFlex []struct {
					Id string `xml:"id,omitempty" json:"id,omitempty"`

					Name string `xml:"name,omitempty" json:"name,omitempty"`

					Value string `xml:"value,omitempty" json:"value,omitempty"`
				} `xml:"AttributeFlex,omitempty" json:"AttributeFlex,omitempty"`
			} `xml:"AttributeFlexArray,omitempty" json:"AttributeFlexArray,omitempty"`

			//
			// customProductMessage5 Message from the supplier regarding the stock
			//

			CustomProductMessage string `xml:"customProductMessage,omitempty" json:"customProductMessage,omitempty"`

			//
			// Record type (exact, alternate)
			//

			EntryType string `xml:"entryType,omitempty" json:"entryType,omitempty"`

			//
			// Datetime inventory is available
			//
			ValidTimestamp time.Time `xml:"validTimestamp,omitempty" json:"validTimestamp,omitempty"`
		} `xml:"ProductCompanionInventory,omitempty" json:"ProductCompanionInventory,omitempty"`
	} `xml:"ProductCompanionInventoryArray,omitempty" json:"ProductCompanionInventoryArray,omitempty"`

	//
	// Response for any error requiring notification to requestor
	//

	ErrorMessage string `xml:"errorMessage,omitempty" json:"errorMessage,omitempty"`

	CustomMessageArray struct {
		CustomMessage string `xml:"customMessage,omitempty" json:"customMessage,omitempty"`
	} `xml:"CustomMessageArray,omitempty" json:"CustomMessageArray,omitempty"`
}

type InventoryService interface {
	GetFilterValues(request *GetFilterValuesRequest) (*GetFilterValuesReply, error)

	GetFilterValuesContext(ctx context.Context, request *GetFilterValuesRequest) (*GetFilterValuesReply, error)

	GetInventoryLevels(request *Request) (*Reply, error)

	GetInventoryLevelsContext(ctx context.Context, request *Request) (*Reply, error)
}

type inventoryService struct {
	client *soap.Client
}

func NewInventoryService(client *soap.Client) InventoryService {
	return &inventoryService{
		client: client,
	}
}

func (service *inventoryService) GetFilterValuesContext(ctx context.Context, request *GetFilterValuesRequest) (*GetFilterValuesReply, error) {
	response := new(GetFilterValuesReply)
	err := service.client.CallContext(ctx, "getFilterValues", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *inventoryService) GetFilterValues(request *GetFilterValuesRequest) (*GetFilterValuesReply, error) {
	return service.GetFilterValuesContext(
		context.Background(),
		request,
	)
}

func (service *inventoryService) GetInventoryLevelsContext(ctx context.Context, request *Request) (*Reply, error) {
	response := new(Reply)
	err := service.client.CallContext(ctx, "getInventoryLevels", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *inventoryService) GetInventoryLevels(request *Request) (*Reply, error) {
	return service.GetInventoryLevelsContext(
		context.Background(),
		request,
	)
}
